/**
 * Snippet type-check for the docs quality gates: every ```ts / ```typescript block of the
 * hand-written pages becomes its own module under `node_modules/.cache/docs-gates/` (gitignored),
 * next to a generated tsconfig extending the repo's `tsconfig.base.json`, and one TypeScript
 * program checks them all. Diagnostics are mapped back to `page.md:line`.
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';
import type { CodeBlock } from './markdown.ts';

/** Languages that are type-checked. */
export const TS_LANGS: ReadonlySet<string> = new Set(['ts', 'typescript']);

/** A snippet extracted from a page. */
export interface Snippet {
  /** Page path relative to the docs root. */
  page: string;
  block: CodeBlock;
}

/** A type error in a snippet. */
export interface SnippetError {
  /** `page.md:line`. */
  location: string;
  message: string;
}

/** Result of gate 4. */
export interface SnippetReport {
  /** ts/typescript blocks found. */
  total: number;
  checked: number;
  /** `page.md:line` of blocks opted out with `<!-- docs-gates: no-typecheck -->`. */
  optedOut: string[];
  errors: SnippetError[];
}

/**
 * Names every snippet may use without declaring them: the conventional context of the docs (a
 * container `el`, a `chart` made with `createChart(el, figure)`, the figure's `data` and `layout`).
 * Snippets that declare or import one of these shadow it, since each snippet is its own module.
 */
export const PRELUDE = `// Generated by scripts/quality (docs snippet type-check). Do not edit.
import type { Chart, FigureInput, Layout, createChart as CreateChart } from '@mk7s/holochart';

declare global {
  /** The chart's container element. */
  const el: HTMLElement;
  /** A chart created with \`createChart(el, figure)\`. */
  const chart: Chart;
  const figure: FigureInput;
  const data: NonNullable<FigureInput['data']>;
  const layout: Layout;
  const createChart: typeof CreateChart;
}

export {};
`;

/** File name of a snippet module: `getting-started/first-chart.md` line 31 → `getting-started__first-chart.L31.ts`. */
export function snippetFileName(page: string, line: number): string {
  return `${page.replace(/\.md$/, '').replace(/[^\w-]+/g, '__')}.L${line}.ts`;
}

/** Module source of a snippet. `export {}` goes last so snippet line N is file line N. */
export function snippetModule(code: string): string {
  return `${code}\nexport {};\n`;
}

/** `name` → absolute `source` entry of every workspace package under `packages/`. */
async function workspacePaths(repoRoot: string): Promise<Record<string, string[]>> {
  const out: Record<string, string[]> = {};
  const dir = path.join(repoRoot, 'packages');
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    try {
      const pkg = JSON.parse(await readFile(path.join(dir, e.name, 'package.json'), 'utf8')) as {
        name?: string;
        exports?: Record<string, unknown>;
      };
      const root = pkg.exports?.['.'] as Record<string, unknown> | undefined;
      const source = root?.['source'];
      if (pkg.name && typeof source === 'string') {
        out[pkg.name] = [path.join(dir, e.name, source)];
      }
    } catch {
      // Not a package.
    }
  }
  return out;
}

/**
 * Type-check snippets. Workspace packages that are not dependencies of the docs app (e.g.
 * `@mk7s/holochart-traces-basic`, which installation instructions import) are mapped to their
 * sources with `paths`, as a user who installed them would see them.
 */
export async function checkSnippets(
  snippets: readonly Snippet[],
  options: { repoRoot: string; cacheDir: string },
): Promise<SnippetReport> {
  const { repoRoot, cacheDir } = options;
  const srcDir = path.join(cacheDir, 'snippets');
  await rm(srcDir, { recursive: true, force: true });
  await mkdir(srcDir, { recursive: true });

  await writeFile(path.join(srcDir, '_prelude.d.ts'), PRELUDE);

  const report: SnippetReport = { total: snippets.length, checked: 0, optedOut: [], errors: [] };
  const byFile = new Map<string, Snippet>();
  for (const s of snippets) {
    if (s.block.noTypecheck) {
      report.optedOut.push(`${s.page}:${s.block.line}`);
      continue;
    }
    const file = path.join(srcDir, snippetFileName(s.page, s.block.line));
    await writeFile(file, snippetModule(s.block.code));
    byFile.set(path.normalize(file), s);
  }
  report.checked = byFile.size;
  if (byFile.size === 0) return report;

  const tsconfig = {
    extends: path.relative(cacheDir, path.join(repoRoot, 'tsconfig.base.json')),
    compilerOptions: {
      noEmit: true,
      declaration: false,
      declarationMap: false,
      sourceMap: false,
      lib: ['ES2023', 'DOM', 'DOM.Iterable'],
      types: [],
      paths: await workspacePaths(repoRoot),
    },
    include: ['snippets/**/*.ts'],
  };
  const configPath = path.join(cacheDir, 'tsconfig.json');
  await writeFile(configPath, `${JSON.stringify(tsconfig, null, 2)}\n`);

  const parsed = ts.getParsedCommandLineOfConfigFile(configPath, undefined, {
    ...ts.sys,
    onUnRecoverableConfigFileDiagnostic: (d) => {
      throw new Error(ts.flattenDiagnosticMessageText(d.messageText, '\n'));
    },
  });
  if (!parsed) throw new Error(`Could not read ${configPath}`);
  const program = ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options });

  const prelude = path.normalize(path.join(srcDir, '_prelude.d.ts'));
  const diagnostics: ts.Diagnostic[] = [...program.getOptionsDiagnostics()];
  for (const sf of program.getSourceFiles()) {
    const file = path.normalize(sf.fileName);
    if (!byFile.has(file) && file !== prelude) continue;
    diagnostics.push(...program.getSyntacticDiagnostics(sf), ...program.getSemanticDiagnostics(sf));
  }
  for (const d of diagnostics) {
    const message = ts.flattenDiagnosticMessageText(d.messageText, '\n  ');
    const snippet = d.file ? byFile.get(path.normalize(d.file.fileName)) : undefined;
    if (!d.file || !snippet || d.start === undefined) {
      report.errors.push({
        location: d.file ? path.basename(d.file.fileName) : 'tsconfig',
        message,
      });
      continue;
    }
    const { line } = d.file.getLineAndCharacterOfPosition(d.start);
    report.errors.push({
      location: `${snippet.page}:${snippet.block.line + 1 + line}`,
      message: `TS${d.code}: ${message}`,
    });
  }
  return report;
}
