// Ambient d3-geo-projection types must also reach programs that compile these sources indirectly
// (a package that depends on this one, the examples).
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path="./d3-geo-projection.d.ts" />
/**
 * The 67 Plotly projections that need `d3-geo-projection` (ADR-026): one lazy chunk, reached only
 * through the dynamic import in `projections.ts`. Each factory is imported by name, so the chunk
 * holds these projections and not the rest of the library (the interrupted and polyhedral ones,
 * `geoProject`, `geoStitch`, …).
 *
 * The names are Plotly's `projection.type` values (plotly.js `src/plots/geo/constants.js`,
 * `projNames`, MIT); `constants.ts` has the same table as strings.
 */
import type { GeoProjection } from 'd3-geo';
import {
  geoAiry,
  geoAitoff,
  geoAugust,
  geoBaker,
  geoBertin1953,
  geoBoggs,
  geoBonne,
  geoBottomley,
  geoBromley,
  geoCollignon,
  geoCraig,
  geoCraster,
  geoCylindricalEqualArea,
  geoCylindricalStereographic,
  geoEckert1,
  geoEckert2,
  geoEckert3,
  geoEckert4,
  geoEckert5,
  geoEckert6,
  geoEisenlohr,
  geoFahey,
  geoFoucaut,
  geoFoucautSinusoidal,
  geoGinzburg4,
  geoGinzburg5,
  geoGinzburg6,
  geoGinzburg8,
  geoGinzburg9,
  geoGringorten,
  geoGringortenQuincuncial,
  geoGuyou,
  geoHammer,
  geoHill,
  geoHomolosine,
  geoHufnagel,
  geoHyperelliptical,
  geoKavrayskiy7,
  geoLagrange,
  geoLarrivee,
  geoLaskowski,
  geoLoximuthal,
  geoMiller,
  geoMollweide,
  geoMtFlatPolarParabolic,
  geoMtFlatPolarQuartic,
  geoMtFlatPolarSinusoidal,
  geoNaturalEarth2,
  geoNellHammer,
  geoNicolosi,
  geoPatterson,
  geoPeirceQuincuncial,
  geoPolyconic,
  geoRectangularPolyconic,
  geoRobinson,
  geoSatellite,
  geoSinuMollweide,
  geoSinusoidal,
  geoTimes,
  geoVanDerGrinten,
  geoVanDerGrinten2,
  geoVanDerGrinten3,
  geoVanDerGrinten4,
  geoWagner4,
  geoWagner6,
  geoWiechel,
  geoWinkel3,
} from 'd3-geo-projection';
import type { ExtraProjectionType } from './constants.ts';

/** Plotly's `projection.type` to the factory of its `d3-geo-projection` projection. */
export const EXTRA_PROJECTIONS: Readonly<Record<ExtraProjectionType, () => GeoProjection>> = {
  airy: geoAiry,
  aitoff: geoAitoff,
  august: geoAugust,
  baker: geoBaker,
  bertin1953: geoBertin1953,
  boggs: geoBoggs,
  bonne: geoBonne,
  bottomley: geoBottomley,
  bromley: geoBromley,
  collignon: geoCollignon,
  craig: geoCraig,
  craster: geoCraster,
  'cylindrical equal area': geoCylindricalEqualArea,
  'cylindrical stereographic': geoCylindricalStereographic,
  eckert1: geoEckert1,
  eckert2: geoEckert2,
  eckert3: geoEckert3,
  eckert4: geoEckert4,
  eckert5: geoEckert5,
  eckert6: geoEckert6,
  eisenlohr: geoEisenlohr,
  fahey: geoFahey,
  'foucaut sinusoidal': geoFoucautSinusoidal,
  foucaut: geoFoucaut,
  ginzburg4: geoGinzburg4,
  ginzburg5: geoGinzburg5,
  ginzburg6: geoGinzburg6,
  ginzburg8: geoGinzburg8,
  ginzburg9: geoGinzburg9,
  'gringorten quincuncial': geoGringortenQuincuncial,
  gringorten: geoGringorten,
  guyou: geoGuyou,
  hammer: geoHammer,
  hill: geoHill,
  homolosine: geoHomolosine,
  hufnagel: geoHufnagel,
  hyperelliptical: geoHyperelliptical,
  kavrayskiy7: geoKavrayskiy7,
  lagrange: geoLagrange,
  larrivee: geoLarrivee,
  laskowski: geoLaskowski,
  loximuthal: geoLoximuthal,
  miller: geoMiller,
  mollweide: geoMollweide,
  'mt flat polar parabolic': geoMtFlatPolarParabolic,
  'mt flat polar quartic': geoMtFlatPolarQuartic,
  'mt flat polar sinusoidal': geoMtFlatPolarSinusoidal,
  'natural earth2': geoNaturalEarth2,
  'nell hammer': geoNellHammer,
  nicolosi: geoNicolosi,
  patterson: geoPatterson,
  'peirce quincuncial': geoPeirceQuincuncial,
  polyconic: geoPolyconic,
  'rectangular polyconic': geoRectangularPolyconic,
  robinson: geoRobinson,
  satellite: geoSatellite,
  'sinu mollweide': geoSinuMollweide,
  sinusoidal: geoSinusoidal,
  times: geoTimes,
  'van der grinten': geoVanDerGrinten,
  'van der grinten2': geoVanDerGrinten2,
  'van der grinten3': geoVanDerGrinten3,
  'van der grinten4': geoVanDerGrinten4,
  wagner4: geoWagner4,
  wagner6: geoWagner6,
  wiechel: geoWiechel,
  'winkel tripel': geoWinkel3,
  winkel3: geoWinkel3,
};
