import { describe, expect, it } from 'vitest';
import {
  finishReport,
  packageStability,
  publicNames,
  reportFileName,
  sortUnions,
  type ReportPackage,
} from './report.ts';

const HEADER = [
  '## API Report File for "@mk7s/demo"',
  '',
  '> Do not edit this file. It is a report generated by [API Extractor](https://api-extractor.com/).',
  '',
  '```ts',
  '',
];
const FOOTER = ['', '// (No @packageDocumentation comment for this package)', '', '```', ''];

function report(...body: string[]): string {
  return [...HEADER, ...body, ...FOOTER].join('\n');
}

/** The TypeScript block of a finished report, without the blank first line and the footer. */
function body(finished: string): string[] {
  const lines = finished.split('\n');
  return lines.slice(lines.indexOf('```ts') + 2, lines.lastIndexOf('```') - 3);
}

const stable: ReportPackage = { name: '@mk7s/demo', stability: 'stable', publicNames: new Set() };
const experimental: ReportPackage = { ...stable, stability: 'experimental' };
const none: ReadonlySet<string> = new Set();

describe('reportFileName', () => {
  it('drops the scope', () => {
    expect(reportFileName('@mk7s/holochart-core')).toBe('holochart-core.api.md');
    expect(reportFileName('holochart')).toBe('holochart.api.md');
  });
});

describe('packageStability', () => {
  it('is experimental when the package comment is tagged', () => {
    const source =
      '/**\n * The render layer.\n *\n * @experimental\n * @packageDocumentation\n */\n';
    expect(packageStability(source)).toBe('experimental');
  });

  it('is stable without a package comment, or without the tag', () => {
    expect(packageStability("/** A helper. @experimental */\nexport * from './a.ts';")).toBe(
      'stable',
    );
    expect(packageStability('/**\n * Core.\n * @packageDocumentation\n */')).toBe('stable');
    // Prose that mentions the tag is not the tag.
    expect(
      packageStability('/**\n * Not `@experimental` any more.\n * @packageDocumentation\n */'),
    ).toBe('stable');
  });
});

describe('publicNames', () => {
  it('lists the declarations tagged @public', () => {
    const names = publicNames(
      [
        '/** The registry. @public */',
        'export declare const fonts: { register(): void };',
        '/**',
        ' * Register a face.',
        ' * @public',
        ' */',
        'declare function registerFont(): void;',
        '/** Untagged. */',
        'export interface Viewport { /** @public */ id: string }',
        '/** @experimental */',
        'export type Rect = [number, number];',
      ].join('\n'),
    );
    expect([...names].sort()).toEqual(['fonts', 'registerFont']);
  });
});

describe('sortUnions', () => {
  it('sorts union members, whatever order the build listed them in', () => {
    const a = sortUnions(`export const mode: AttrSpec<"none" | "lines" | \`lines+\${string}\`>;`);
    const b = sortUnions(`export const mode: AttrSpec<\`lines+\${string}\` | "none" | "lines">;`);
    expect(a).toBe(b);
    expect(a).toBe(`export const mode: AttrSpec<"lines" | "none" | \`lines+\${string}\`>;`);
  });

  it('sorts nested unions and leaves everything else alone', () => {
    expect(
      sortUnions('type T = { b: "y" | "x"; a: readonly ("v" | "h")[] | undefined } | null;'),
    ).toBe('type T = null | { b: "x" | "y"; a: readonly ("h" | "v")[] | undefined };');
  });

  it('drops a leading bar and line breaks', () => {
    expect(sortUnions('type T =\n    | "b"\n    | "a";')).toBe('type T =\n    "a" | "b";');
  });

  it('keeps a union with comments between its members as written', () => {
    const code = 'type T = "b" /* second */ | "a" | ("d" | "c");';
    expect(sortUnions(code)).toBe('type T = "b" /* second */ | "a" | ("c" | "d");');
  });
});

describe('finishReport', () => {
  it('adds the stability note under the header and ends with one newline', () => {
    const finished = finishReport(report('// @public\nexport const a: number;'), stable, none);
    const lines = finished.split('\n');
    expect(lines[3]).toBe('>');
    expect(lines[4]).toMatch(/^> Stability: exports are stable/);
    expect(finished.endsWith('```\n')).toBe(true);
    expect(finished.endsWith('\n\n')).toBe(false);
    expect(finishReport(report('// @public\nexport const a: number;'), experimental, none)).toMatch(
      /> Stability: \*\*experimental\*\*/,
    );
  });

  it('normalizes CRLF', () => {
    const crlf = report('// @public', 'export const a: number;').replace(/\n/g, '\r\n');
    expect(finishReport(crlf, stable, none)).not.toContain('\r');
  });

  it('shows @experimental instead of API Extractor’s @public on tagged declarations', () => {
    const finished = finishReport(
      report(
        '// @public',
        'export function createChart(): Chart;',
        '',
        '// @public @experimental',
        'export interface TraceModule {',
        '    // @experimental (undocumented)',
        '    plot: unknown;',
        '}',
        '',
        '// @public @deprecated @experimental (undocumented)',
        'export type Old = string;',
      ),
      stable,
      none,
    );
    expect(body(finished)).toEqual([
      '// @public',
      'export function createChart(): Chart;',
      '',
      '// @experimental',
      'export interface TraceModule {',
      '    // @experimental (undocumented)',
      '    plot: unknown;',
      '}',
      '',
      '// @deprecated @experimental (undocumented)',
      'export type Old = string;',
    ]);
  });

  it('marks the untagged declarations of an experimental package, keeping @public ones', () => {
    const finished = finishReport(
      report(
        '// Warning: (ae-forgotten-export) The symbol "Rect" needs to be exported by the entry point index.d.ts',
        '//',
        '// @public (undocumented)',
        'export class Viewport {',
        '    // (undocumented)',
        '    rect: Rect;',
        '}',
        '',
        '// @public',
        'export const fonts: {',
        '    register(): void;',
        '};',
        '',
        '// @public',
        'export function pick(x: number): number;',
        '',
        '// @public',
        'export function pick(x: string): string;',
        '',
        '// @public',
        'type Rect = [number, number];',
      ),
      { ...experimental, publicNames: new Set(['fonts']) },
      none,
    );
    expect(body(finished)).toEqual([
      '// Warning: (ae-forgotten-export) The symbol "Rect" needs to be exported by the entry point index.d.ts',
      '//',
      '// @experimental (undocumented)',
      'export class Viewport {',
      '    // (undocumented)',
      '    rect: Rect;',
      '}',
      '',
      '// @public',
      'export const fonts: {',
      '    register(): void;',
      '};',
      '',
      '// @experimental',
      'export function pick(x: number): number;',
      '',
      '// @experimental',
      'export function pick(x: string): string;',
      '',
      '// @experimental',
      'type Rect = [number, number];',
    ]);
  });

  it('marks a namespace re-exported from an experimental package', () => {
    const finished = finishReport(
      report(
        "import * as express from '@mk7s/holochart-express';",
        "import * as render from '@mk7s/holochart-render';",
        '',
        'export { express }',
        '',
        'export { render }',
      ),
      stable,
      new Set(['@mk7s/holochart-render']),
    );
    expect(body(finished).slice(3)).toEqual([
      'export { express }',
      '',
      '// @experimental (every export of the package, unless marked @public there)',
      'export { render }',
    ]);
  });

  it('is idempotent on its own output apart from the header note', () => {
    const once = finishReport(
      report('// @public @experimental', 'export type A = "b" | "a";'),
      stable,
      none,
    );
    expect(body(finishReport(once, stable, none))).toEqual(body(once));
  });
});
