/**
 * The public API shared by the full bundle (`index.ts`) and the 2D bundle of the script-tag build
 * (`bundle-2d.ts`): everything but the built-in module list, their registration and the 3D
 * package (`exports-3d.ts`). No side effects.
 *
 * Every name is listed: what a chart user needs (the chart API, typed figures, the modules to
 * register, themes, errors, documented helpers) and the `@experimental` plugin API. The packages
 * also export the plumbing they share, tagged `@internal` (docs/release/versioning.md); it is
 * left out here, so it is not a name of `@mk7s/holochart`. A new stable or experimental export
 * of a package has to be added to its list below (`pnpm api:check` fails until it is).
 */
import type { Config } from '@mk7s/holochart-core';
import * as runtime from '@mk7s/holochart-runtime';
import type {
  AttributeUpdate,
  Chart,
  ChartOptions,
  DownloadImageOptions,
  LayoutUpdate,
  ToImageOptions,
  TraceIndices,
} from '@mk7s/holochart-runtime';
import type { Figure } from './figure.ts';
import type { Data, Layout } from './generated/figure.ts';

// Core: the figure model, validation, defaults, templates, colors, and the schema DSL.
export {
  attr,
  BUILTIN_COLORSCALE_GROUPS,
  BUILTIN_PALETTES,
  canonicalColor,
  cartesianTraceAttributes,
  CARTO_DIVERGING,
  CARTO_SEQUENTIAL,
  CMOCEAN_CYCLICAL,
  CMOCEAN_DIVERGING,
  CMOCEAN_SEQUENTIAL,
  COLORBREWER_DIVERGING,
  COLORBREWER_SEQUENTIAL,
  colors,
  colorscaleNames,
  colorwayNames,
  colorways,
  commonTraceAttributes,
  composeTemplates,
  configSchema,
  createRegistry,
  CYCLICAL,
  decodeFigure,
  decodeTypedArray,
  diffFigures,
  DIVERGING_PLOTLY,
  domainTraceAttributes,
  EDIT_FLAGS,
  encodeFigure,
  encodeTypedArray,
  evenStops,
  extrusionAttributes,
  FACET_LABEL_NAME,
  fontSchema,
  formatDate,
  formatIssue,
  getColorscale,
  getColorway,
  HOLOCHART_COLORWAY,
  HOLOCHART_FONT_FAMILY,
  HolochartError,
  holochartTemplate,
  isColorscaleName,
  isDateString,
  isValidColor,
  isValidDate,
  layoutSchema,
  litMaterialAttributes,
  makeSubplots,
  noneTemplate,
  parseDate,
  planRelayout,
  planRestyle,
  planUpdate,
  plotlyClassicTemplate,
  PLOTLYJS_COLORSCALES,
  plotSchema,
  QUALITATIVE,
  registerBuiltinColors,
  registerColorscale,
  registerColorscales,
  registerColorway,
  resolveTemplate,
  reverseColorscale,
  schemaToJSON,
  SEQUENTIAL,
  supplyDefaults,
  toRGBA,
  toRGBAArray,
  VAL_TYPES,
  validate,
  ValidationError,
  withExtrusion,
  xaxisSchema,
  yaxisSchema,
} from '@mk7s/holochart-core';
export type {
  AnyFigure,
  AnyFunction,
  AnyOptions,
  AttrBuilders,
  AttrConstraints,
  AttrRole,
  AttrSpec,
  AxisExtremes,
  AxisType,
  BaseLayout,
  BaseLayoutTitle,
  BooleanOptions,
  BreakMap,
  CalendarSystem,
  CartesianTraceAttributes,
  Change,
  Children,
  ColorlistOptions,
  ColorOptions,
  ColorScale,
  ColorscaleGroup,
  ColorscaleInput,
  ColorscaleKind,
  ColorscaleOptions,
  ColorscaleStops,
  CommonTraceAttributes,
  Config,
  ConfigA11y,
  ConfigEdits,
  ConfigToImageButtonOptions,
  CoreComponentModule,
  CoreTraceModule,
  DataArray,
  DataArrayOptions,
  DataColumn,
  DatasetRef,
  DecodedArray,
  DomainTraceAttributes,
  Dtype,
  EditFlag,
  EditType,
  EncodedFigure,
  EncodedTypedArray,
  EncodeFigureOptions,
  EnumeratedOptions,
  Extent,
  ExtremePoint,
  ExtrusionAttributes,
  ExtrusionBevel,
  ExtrusionMaterial,
  FigureDiff,
  FigureInput,
  FlaglistOptions,
  FrameInput,
  FullAxis,
  FullConfig,
  FullGrid,
  FullItemExtras,
  FullLayout,
  FullTrace,
  FunctionOptions,
  InferFull,
  InferInput,
  InfoArrayOptions,
  Issue,
  IssueCode,
  ItemsNode,
  ItemsOptions,
  JSONSchemaNode,
  JSONValue,
  LayoutDefaultsContext,
  LayoutFont,
  LayoutGrid,
  LayoutGridDomain,
  LayoutInput,
  LayoutMargin,
  LayoutSelection,
  LayoutSelectionLine,
  LayoutTitleFont,
  LayoutTransition,
  LayoutUniformtext,
  LayoutXaxis,
  LayoutXaxisAutorangeoptions,
  LayoutXaxisMinor,
  LayoutXaxisRangebreak,
  LayoutXaxisRangeselector,
  LayoutXaxisRangeselectorButton,
  LayoutXaxisRangeselectorFont,
  LayoutXaxisRangeslider,
  LayoutXaxisRangesliderYaxis,
  LayoutXaxisTickfont,
  LayoutXaxisTickformatstop,
  LayoutXaxisTitle,
  LayoutXaxisTitleFont,
  LayoutYaxis,
  LayoutYaxisAutorangeoptions,
  LayoutYaxisMinor,
  LayoutYaxisRangebreak,
  LayoutYaxisTickfont,
  LayoutYaxisTickformatstop,
  LayoutYaxisTitle,
  LayoutYaxisTitleFont,
  Locale,
  LocaleDefinition,
  LocaleDefinitions,
  LocaleFormat,
  LocaleModule,
  LocaleStore,
  MakeSubplotsOptions,
  MakeSubplotsResult,
  NodeMeta,
  NumberOptions,
  ObjectNode,
  PerPoint,
  PerPointColor,
  PerPointNumber,
  PlacedTrace,
  PlaceOptions,
  PlanOptions,
  PlotSchema,
  PointStyleFunction,
  PrimitiveValue,
  ReducedMotion,
  Registry,
  ResolvedTemplate,
  RGBAColor,
  Scale,
  SchemaNode,
  SerializeWarning,
  SerializeWarningCode,
  SharedAxes,
  Stage,
  StringOptions,
  StyleCondition,
  StyleFunction,
  StyleOperators,
  StylePoint,
  StyleRule,
  StyleValue,
  SubplotCell,
  SubplotIdOptions,
  Subplots,
  SubplotSpec,
  SubplotType,
  SupplyDefaultsOptions,
  SupplyDefaultsResult,
  SupportedSubplotType,
  Template,
  TemplatedItemChildren,
  TemplateSource,
  Tick,
  TraceAxisHints,
  TraceCategory,
  TraceDefaultsContext,
  TraceDomain,
  TraceHoverlabel,
  TraceHoverlabelFont,
  TraceInput,
  TraceLegendgrouptitle,
  TraceLegendgrouptitleFont,
  TraceMatch,
  TraceMatching,
  TraceModuleMeta,
  TypedArray,
  TypedArrayConstructor,
  TypedArraySpec,
  ValidateOptions,
  ValType,
} from '@mk7s/holochart-core';

// The runtime: charts, events, animation, export, and the contracts plugins implement. Its
// Plotly-style functions are declared below, typed against this bundle's figures.
export {
  accessibleText,
  addFrames,
  animate,
  animateCamera,
  Chart,
  countText,
  createChartRegistry,
  createLatestQueue,
  dataTransform,
  defineTemplate,
  deleteFrames,
  domainRect,
  DRAW_DRAGMODES,
  figureFromJSON,
  fitAspect,
  formatAxisValue,
  formatPlainNumber,
  formatTemplate,
  Fx,
  fxComponent,
  fxLayoutAttributes,
  getChart,
  hover,
  inscribedCircle,
  isDrawDragmode,
  linearExtremes,
  linearToPosition,
  listText,
  MAX_TABLE_ROWS,
  MIN_PLOT_SIZE,
  parseSelectionPath,
  polygonContains,
  positionToLinear,
  selectionContains,
  selectionFromQuery,
  selectionQuery,
  selectionsOf,
  splitExtra,
  STACK_GROUPS,
  traceNameText,
  unhover,
  WebGLUnavailableError,
} from '@mk7s/holochart-runtime';
export type {
  AnimateTarget,
  AnimatingFrameEvent,
  AnimationOptions,
  AnnotationEventData,
  AttributeUpdate,
  AxisInfo,
  BinsInsight,
  BoxesInsight,
  CalcContext,
  CameraAnimationOptions,
  CameraAnimationRun,
  CameraTarget,
  CameraVector,
  CanonicalEvent,
  ChartDescription,
  ChartEventKey,
  ChartEventName,
  ChartEvents,
  ChartFigureSource,
  ChartListener,
  ChartOptions,
  ChartPoint,
  ChartRegistry,
  ChartRegistryOptions,
  ChartThree,
  ChartToJSONOptions,
  ColorbarSpec,
  ComponentDrawContext,
  ComponentExtremesContext,
  ComponentLayoutContext,
  ComponentModule,
  ComponentPointerEvent,
  ComponentRenderer,
  ComponentUpdatePlan,
  ComponentView,
  ComputedFrame,
  CrossTraceContext,
  CrossTraceEntry,
  DescribeContext,
  DescribedTable,
  DomainInfo,
  DomainLayoutContext,
  DomainTraceEntry,
  DoubleClickAction,
  DownloadImageOptions,
  Dragmode,
  DrawDragmode,
  DrawGesture,
  EasingName,
  FigurePatch,
  FrameOptions,
  FullSelection,
  FxSettings,
  GridInsight,
  HierarchyClickEventData,
  HoverContext,
  Hovermode,
  HoverPoint,
  HoverQuery,
  ImageFormat,
  KeyboardPoint,
  KeyboardStops,
  LatestQueue,
  LayoutTween,
  LayoutUpdate,
  LegendEventData,
  LegendGlyph,
  LegendGlyphPart,
  LegendIconContext,
  LegendItem,
  MarginPush,
  MaxPoints,
  PointerEventData,
  PricesInsight,
  Registrable,
  RegistryListing,
  SelectArea,
  SelectionEventData,
  SelectionQuery,
  SeriesInsight,
  SharesInsight,
  StreamUpdate,
  SubplotInfo,
  SubplotMirror,
  SubplotMirrorOptions,
  SubplotViewportOptions,
  TemplateContext,
  TemplateModule,
  TemplateOptions,
  ToImageOptions,
  TraceA11y,
  TraceA11yParts,
  TraceAppend,
  TraceCellRef,
  TraceDescription,
  TraceExtremes,
  TraceIndices,
  TraceInsight,
  TraceModule,
  TracePlotContext,
  TraceRenderer,
  TraceUpdatePlan,
  TraceView,
  TransitionOptions,
  ValueInsight,
} from '@mk7s/holochart-runtime';

/**
 * Figure types (backlog S1.6): `Figure`, `Frame`, `Data` (every built-in trace type) and `Layout`
 * (every layout attribute of the bundle's traces and components). The packages' own types of the
 * traces and the layout this bundle extends have other names (core's `BaseLayout`,
 * `traces-basic`'s `BaseBarTrace` without the 2.5D attributes, …).
 */
export type { Figure, Frame } from './figure.ts';
export type * from './generated/figure.ts';

// The entry points are re-bound locally (not only re-exported) so that using any of them keeps the
// bundle module, and with it the registration of the built-ins, in a tree-shaken build
// ("sideEffects": false). The ones taking figures are typed against this bundle's `Figure`,
// `Data` and `Layout` (types only: the functions are the runtime's).

/** Create a chart in `el` (see the runtime's `createChart`), its figure typed as a {@link Figure}. */
export const createChart: (el: HTMLElement, figure?: Figure, options?: ChartOptions) => Chart =
  runtime.createChart;
/** Draw a new chart in `el`: Plotly's `(el, data, layout?, config?)` or `(el, figure)`. */
export const newPlot: (
  el: HTMLElement,
  dataOrFigure?: readonly Data[] | Figure,
  layout?: Layout,
  config?: Config,
  options?: ChartOptions,
) => Promise<Chart> = runtime.newPlot;
/** Update `el` to show a new figure efficiently (diffing), or create the chart if needed. */
export const react: (
  el: HTMLElement,
  dataOrFigure?: readonly Data[] | Figure,
  layout?: Layout,
  config?: Config,
  options?: ChartOptions,
) => Promise<Chart> = runtime.react;
/**
 * Plotly `restyle`: attribute paths (`'marker.color'`) whose array values hold one value per
 * trace, so the update is not typed against the traces (`AttributeUpdate`).
 */
export const restyle = runtime.restyle;
/** Plotly `relayout`: attribute paths (untyped) and whole layout attributes (typed). */
export const relayout: (el: HTMLElement, update: LayoutUpdate<Layout>) => Promise<Chart> =
  runtime.relayout;
/** Plotly `update`: `restyle` and `relayout` in one step. */
export const update: (
  el: HTMLElement,
  traceUpdate?: AttributeUpdate,
  layoutUpdate?: LayoutUpdate<Layout>,
  traces?: TraceIndices,
) => Promise<Chart> = runtime.update;
/** Plotly `addTraces`: add traces at the end, or at `newIndices`. */
export const addTraces: (
  el: HTMLElement,
  traces: Data | readonly Data[],
  newIndices?: TraceIndices,
) => Promise<Chart> = runtime.addTraces;
export const deleteTraces = runtime.deleteTraces;
export const moveTraces = runtime.moveTraces;
export const extendTraces = runtime.extendTraces;
export const prependTraces = runtime.prependTraces;
export const fromJSON = runtime.fromJSON;
export const chartToJSON = runtime.chartToJSON;
/** Plotly's `toImage`: render the chart in `el`, or a figure drawn offscreen, to a data URL. */
export const toImage: (
  target: HTMLElement | Figure,
  options?: ToImageOptions,
  chartOptions?: ChartOptions,
) => Promise<string> = runtime.toImage;
/** Plotly's `downloadImage`: {@link toImage} and save the file. Resolves to the file name. */
export const downloadImage: (
  target: HTMLElement | Figure,
  options?: DownloadImageOptions,
  chartOptions?: ChartOptions,
) => Promise<string> = runtime.downloadImage;
export const purge = runtime.purge;
export const register = runtime.register;
export const registry = runtime.registry;
export const setDefaultTemplate = runtime.setDefaultTemplate;

// The 2D trace packages: the modules to register, their trace types, attribute schemas and calc
// types, and the figure helpers (`timeline`, `strip`, `bubbleSizeref`).
export {
  bar,
  barAttributes,
  basicTraces,
  bubbleSizeref,
  colorbarAttributes,
  pie,
  pieAttributes,
  scatter,
  scatterAttributes,
  table,
  tableAttributes,
  timeline,
} from '@mk7s/holochart-traces-basic';
export type {
  BarCalc,
  BarTraceErrorX,
  BarTraceErrorY,
  BarTraceInsidetextfont,
  BarTraceMarker,
  BarTraceMarkerLine,
  BarTraceMarkerPattern,
  BarTraceOutsidetextfont,
  BarTraceSelected,
  BarTraceSelectedMarker,
  BarTraceSelectedTextfont,
  BarTraceTextfont,
  BarTraceUnselected,
  BarTraceUnselectedMarker,
  BarTraceUnselectedTextfont,
  BaseBarTrace,
  BasePieTrace,
  BaseScatterTrace,
  BubbleSizerefOptions,
  Colorbar,
  ColorbarTickfont,
  ColorbarTitle,
  ColorbarTitleFont,
  PieCalc,
  PieLayout,
  PieSlice,
  PieTraceInsidetextfont,
  PieTraceMarker,
  PieTraceMarkerLine,
  PieTraceMarkerPattern,
  PieTraceOutsidetextfont,
  PieTraceTextfont,
  PieTraceTitle,
  PieTraceTitleFont,
  ScatterCalc,
  ScatterLink,
  ScatterStack,
  ScatterTraceErrorX,
  ScatterTraceErrorY,
  ScatterTraceFillgradient,
  ScatterTraceFillpattern,
  ScatterTraceLine,
  ScatterTraceMarker,
  ScatterTraceMarkerLine,
  ScatterTraceSelected,
  ScatterTraceSelectedMarker,
  ScatterTraceSelectedTextfont,
  ScatterTraceTextfont,
  ScatterTraceUnselected,
  ScatterTraceUnselectedMarker,
  ScatterTraceUnselectedTextfont,
  StackOutput,
  TableCalc,
  TableColumn,
  TableTrace,
  TableTraceCells,
  TableTraceCellsFill,
  TableTraceCellsFont,
  TableTraceCellsLine,
  TableTraceHeader,
  TableTraceHeaderFill,
  TableTraceHeaderFont,
  TableTraceHeaderLine,
  TimelineData,
  TimelineFigure,
  TimelineFigureOptions,
  TracesBasic,
} from '@mk7s/holochart-traces-basic';
export {
  box,
  boxAttributes,
  histogram,
  histogram2d,
  histogram2dAttributes,
  histogram2dcontour,
  histogram2dcontourAttributes,
  histogramAttributes,
  parcats,
  parcatsAttributes,
  parcoords,
  parcoordsAttributes,
  splom,
  splomAttributes,
  statsTraces,
  strip,
  violin,
  violinAttributes,
} from '@mk7s/holochart-traces-stats';
export type {
  BoxCalc,
  BoxTrace,
  BoxTraceLine,
  BoxTraceMarker,
  BoxTraceMarkerLine,
  BoxTraceSelected,
  BoxTraceSelectedMarker,
  BoxTraceUnselected,
  BoxTraceUnselectedMarker,
  ContourBounds,
  ContourConstraint,
  ContourField,
  ContourLevels,
  ContourPath,
  ContourRegion,
  Histogram2dAxisBins,
  Histogram2dCalc,
  Histogram2dContourCalc,
  Histogram2dcontourTrace,
  Histogram2dcontourTraceContours,
  Histogram2dcontourTraceContoursLabelfont,
  Histogram2dcontourTraceLine,
  Histogram2dcontourTraceMarker,
  Histogram2dcontourTraceXbins,
  Histogram2dcontourTraceYbins,
  Histogram2dTrace,
  Histogram2dTraceMarker,
  Histogram2dTraceTextfont,
  Histogram2dTraceXbins,
  Histogram2dTraceYbins,
  HistogramCalc,
  HistogramTrace,
  HistogramTraceCumulative,
  HistogramTraceXbins,
  HistogramTraceYbins,
  ParcatsCalc,
  ParcatsTrace,
  ParcatsTraceDimension,
  ParcatsTraceLabelfont,
  ParcatsTraceLine,
  ParcatsTraceTickfont,
  ParcoordsCalc,
  ParcoordsDimension,
  ParcoordsTrace,
  ParcoordsTraceDimension,
  ParcoordsTraceLabelfont,
  ParcoordsTraceLine,
  ParcoordsTraceRangefont,
  ParcoordsTraceTickfont,
  ParcoordsTraceUnselected,
  ParcoordsTraceUnselectedLine,
  SplomCalc,
  SplomTrace,
  SplomTraceDiagonal,
  SplomTraceDimension,
  SplomTraceDimensionAxis,
  SplomTraceMarker,
  SplomTraceSelected,
  SplomTraceUnselected,
  StripData,
  StripFigure,
  StripFigureOptions,
  TracesStats,
  ViolinCalc,
  ViolinTrace,
  ViolinTraceBox,
  ViolinTraceBoxLine,
  ViolinTraceLine,
  ViolinTraceMarker,
  ViolinTraceMarkerLine,
  ViolinTraceMeanline,
  ViolinTraceSelected,
  ViolinTraceSelectedMarker,
  ViolinTraceUnselected,
  ViolinTraceUnselectedMarker,
} from '@mk7s/holochart-traces-stats';
export {
  barpolar,
  barpolarAttributes,
  contour,
  contourAttributes,
  heatmap,
  heatmapAttributes,
  image,
  imageAttributes,
  polarAttributes,
  polarComponent,
  PolarSubplot,
  scatterpolar,
  scatterpolarAttributes,
  sciTraces,
} from '@mk7s/holochart-traces-sci';
export type {
  BarpolarTrace,
  BarpolarTraceMarker,
  BaseHeatmapTrace,
  Colormodel,
  ContourTrace,
  ContourTraceCalc,
  ContourTraceContours,
  ContourTraceContoursLabelfont,
  ContourTraceLine,
  HeatmapAxisCells,
  HeatmapCalc,
  ImageCalc,
  ImageTrace,
  ScatterpolarCalc,
  ScatterpolarTrace,
  ScatterpolarTraceLine,
  TracesSci,
} from '@mk7s/holochart-traces-sci';
export {
  candlestick,
  candlestickAttributes,
  financeTraces,
  funnel,
  funnelarea,
  funnelareaAttributes,
  funnelAttributes,
  indicator,
  indicatorAttributes,
  ohlc,
  ohlcAttributes,
  waterfall,
  waterfallAttributes,
} from '@mk7s/holochart-traces-finance';
export type {
  BaseFunnelTrace,
  BaseWaterfallTrace,
  CandlestickTrace,
  CandlestickTraceDecreasing,
  CandlestickTraceDecreasingLine,
  CandlestickTraceHoverlabel,
  CandlestickTraceIncreasing,
  CandlestickTraceIncreasingLine,
  CandlestickTraceLine,
  FunnelareaCalc,
  FunnelareaSlice,
  FunnelareaTrace,
  FunnelareaTraceMarker,
  FunnelareaTraceMarkerLine,
  FunnelareaTraceMarkerPattern,
  FunnelareaTraceTitle,
  FunnelCalc,
  FunnelTraceConnector,
  FunnelTraceConnectorLine,
  FunnelTraceMarker,
  IndicatorCalc,
  IndicatorTrace,
  IndicatorTraceDelta,
  IndicatorTraceDeltaDecreasing,
  IndicatorTraceDeltaFont,
  IndicatorTraceDeltaIncreasing,
  IndicatorTraceGauge,
  IndicatorTraceGaugeAxis,
  IndicatorTraceGaugeAxisTickfont,
  IndicatorTraceGaugeAxisTickformatstop,
  IndicatorTraceGaugeBar,
  IndicatorTraceGaugeBarLine,
  IndicatorTraceGaugeStep,
  IndicatorTraceGaugeStepLine,
  IndicatorTraceGaugeThreshold,
  IndicatorTraceGaugeThresholdLine,
  IndicatorTraceNumber,
  IndicatorTraceNumberFont,
  IndicatorTraceTitle,
  IndicatorTraceTitleFont,
  OhlcTrace,
  OhlcTraceDecreasing,
  OhlcTraceDecreasingLine,
  OhlcTraceHoverlabel,
  OhlcTraceIncreasing,
  OhlcTraceIncreasingLine,
  OhlcTraceLine,
  PriceCalc,
  PriceSlot,
  TracesFinance,
  WaterfallCalc,
  WaterfallTraceConnector,
  WaterfallTraceConnectorLine,
  WaterfallTraceDecreasing,
  WaterfallTraceDecreasingMarker,
  WaterfallTraceDecreasingMarkerLine,
  WaterfallTraceIncreasing,
  WaterfallTraceIncreasingMarker,
  WaterfallTraceIncreasingMarkerLine,
  WaterfallTraceTotals,
  WaterfallTraceTotalsMarker,
  WaterfallTraceTotalsMarkerLine,
} from '@mk7s/holochart-traces-finance';
export {
  buildHierarchy,
  hierTraces,
  icicle,
  icicleAttributes,
  nodePath,
  partition,
  sankey,
  sankeyAttributes,
  sankeyLayout,
  sunburst,
  sunburstAttributes,
  treemap,
  treemapAttributes,
} from '@mk7s/holochart-traces-hier';
export type {
  BaseIcicleTrace,
  BaseTreemapTrace,
  Hierarchy,
  HierarchyInput,
  HierarchyResult,
  HierNode,
  IcicleTraceInsidetextfont,
  IcicleTraceLeaf,
  IcicleTraceMarker,
  IcicleTraceMarkerLine,
  IcicleTraceMarkerPattern,
  IcicleTraceOutsidetextfont,
  IcicleTracePathbar,
  IcicleTracePathbarTextfont,
  IcicleTraceRoot,
  IcicleTraceTextfont,
  IcicleTraceTiling,
  PartitionCell,
  RectCalc,
  RectLayout,
  SankeyCalc,
  SankeyGraph,
  SankeyLayoutOptions,
  SankeyTrace,
  SankeyTraceLink,
  SankeyTraceLinkConcentrationscales,
  SankeyTraceLinkFlow,
  SankeyTraceLinkLine,
  SankeyTraceNode,
  SankeyTraceNodeLine,
  SankeyTraceTextfont,
  SunburstCalc,
  SunburstLayout,
  SunburstTrace,
  SunburstTraceInsidetextfont,
  SunburstTraceLeaf,
  SunburstTraceMarker,
  SunburstTraceMarkerLine,
  SunburstTraceMarkerPattern,
  SunburstTraceOutsidetextfont,
  SunburstTraceRoot,
  SunburstTraceTextfont,
  TracesHier,
  TreemapTraceInsidetextfont,
  TreemapTraceMarker,
  TreemapTraceMarkerLine,
  TreemapTraceMarkerPad,
  TreemapTraceMarkerPattern,
  TreemapTraceOutsidetextfont,
  TreemapTracePathbar,
  TreemapTracePathbarTextfont,
  TreemapTraceRoot,
  TreemapTraceTextfont,
  TreemapTraceTiling,
} from '@mk7s/holochart-traces-hier';
// Components: the modules to register, the shape helpers and the events of the controls.
export {
  addHline,
  addHrect,
  addShape,
  addVline,
  addVrect,
  annotationsComponent,
  axesComponent,
  builtinComponents,
  colorbarComponent,
  componentsReady,
  imagesComponent,
  legendComponent,
  modebarComponent,
  modebarIcons,
  rangeselectorComponent,
  rangesliderComponent,
  selectionsComponent,
  shapesComponent,
  slidersComponent,
  titleComponent,
  updatemenusComponent,
} from '@mk7s/holochart-components';
export type {
  ButtonClickedEvent,
  FullSlider,
  FullSliderStep,
  FullUpdatemenu,
  FullUpdatemenuButton,
  ModebarIcon,
  ShapeOptions,
  SliderChangeEvent,
  SliderEndEvent,
  SliderStartEvent,
} from '@mk7s/holochart-components';
/**
 * The 2.5D view (`layout.view3d`) and extruded bars and areas (`depth`; plan E8.9, E9.10), and
 * pies, treemaps and icicles with depth and a tilt of their own (E9.12), registered by the full
 * bundle (not in `basic`).
 */
export {
  extrudedBar,
  extrudedIcicle,
  extrudedPie,
  extrudedScatter,
  extrudedTreemap,
  view3dAttributes,
  view3dComponent,
  view3dEnabled,
} from './view3d/index.ts';
/** The built-in themes (plan E8.1), namespaced: `themes.THEMES`, `themes.plotly_dark`, … */
export * as themes from '@mk7s/holochart-themes';
/**
 * Plotly Express-style charts from tabular data (plan E23), namespaced because its `scatter`,
 * `strip`, `box`, … share names with the trace modules above: `express.scatter(rows, { x, y })`.
 */
export * as express from '@mk7s/holochart-express';
/** Web fonts for chart text (plan E8.3): `fonts.register('Inter', { regular, bold, … })`. */
export { fonts } from '@mk7s/holochart-render';
/**
 * Custom marker symbols (plan E8.11): `symbols.register('pin', { path: 'M…' })` makes `'pin'` (and
 * `'pin-open'`, …) a `marker.symbol` value.
 */
export { symbols } from '@mk7s/holochart-render';

/**
 * Low-level GPU primitives and the render root, for plugin authors and custom traces (plan E22).
 * Namespaced: the package is large, and experimental as a whole.
 *
 * @experimental
 */
export * as render from '@mk7s/holochart-render';
