<script setup lang="ts">
/**
 * The example gallery (plan E19.5): a thumbnail grid of every example that is a visual test,
 * filterable by category, trace type, tag and "3D-native", with a title search. Thumbnails and
 * their manifest are generated by `tools/gallery-gen` (see `apps/docs/README.md`).
 *
 * Selecting a card opens a detail view with the example running live (`<Example>`), its source,
 * and links to the docs pages that embed it. The open example is kept in the URL hash
 * (`/gallery/#scatter/basic`) and the filters in the query string, so both can be shared.
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { withBase } from 'vitepress';
import { data } from '../data/gallery.data.ts';
import Example from './Example.vue';

type Entry = (typeof data.examples)[number];

/** Categories that are not chart types, in display order after the chart types. */
const CATEGORY_LABELS: Record<string, string> = {
  recipes: 'Recipes',
  demos: 'Demos',
  themes: 'Themes',
  _dev: 'Internals',
};
/** Low-level renderer and component tests: hidden unless asked for. */
const INTERNAL_CATEGORY = '_dev';

const examples = data.examples;

function categoryLabel(category: string): string {
  return CATEGORY_LABELS[category] ?? category.charAt(0).toUpperCase() + category.slice(1);
}

/** "Scatter: markers and lines" → "Markers and lines" (the category is shown above it). */
function shortTitle(title: string): string {
  const rest = title.includes(': ') ? title.slice(title.indexOf(': ') + 2) : title;
  return rest.charAt(0).toUpperCase() + rest.slice(1);
}

/** Trace types shown on a card, without the one its category already names ("Pie · pie"). */
function cardTraces(e: Entry): string[] {
  return e.traceTypes.filter((t) => t !== e.category);
}

function countBy(values: Iterable<string>): Map<string, number> {
  const counts = new Map<string, number>();
  for (const v of values) counts.set(v, (counts.get(v) ?? 0) + 1);
  return counts;
}

const categoryCounts = countBy(examples.map((e) => e.category));
const categories = [...categoryCounts.keys()].sort((a, b) => {
  const rank = (c: string): number =>
    c in CATEGORY_LABELS ? Object.keys(CATEGORY_LABELS).indexOf(c) + 1 : 0;
  return rank(a) - rank(b) || a.localeCompare(b);
});
const allTraceTypes = new Set(examples.flatMap((e) => e.traceTypes));
const allTags = new Set(examples.flatMap((e) => e.tags));
const internalCount = categoryCounts.get(INTERNAL_CATEGORY) ?? 0;

// ---- filters -------------------------------------------------------------------------------

const query = ref('');
const category = ref('');
const trace = ref('');
const tag = ref('');
const threeD = ref(false);
const internal = ref(false);

/** Examples in the selected category (internal tests only when asked for). */
const pool = computed<Entry[]>(() =>
  examples.filter((e) =>
    category.value
      ? e.category === category.value
      : e.category !== INTERNAL_CATEGORY || internal.value,
  ),
);
// Trace type, tag and 3D counts describe the current pool, so a chip never promises examples
// that the category selection hides.
const traceCounts = computed(() => countBy(pool.value.flatMap((e) => e.traceTypes)));
/** Keeps the selected value listed even when the pool has none, so it can be turned off. */
function withSelected(keys: Iterable<string>, selectedValue: string): string[] {
  const out = new Set(keys);
  if (selectedValue) out.add(selectedValue);
  return [...out];
}
const traceTypes = computed(() => withSelected(traceCounts.value.keys(), trace.value).sort());
const tagCounts = computed(() => countBy(pool.value.flatMap((e) => e.tags)));
const tags = computed(() =>
  withSelected(tagCounts.value.keys(), tag.value).sort(
    (a, b) => (tagCounts.value.get(b) ?? 0) - (tagCounts.value.get(a) ?? 0) || a.localeCompare(b),
  ),
);
const threeDCount = computed(() => pool.value.filter((e) => e.threeD).length);

const filtered = computed<Entry[]>(() => {
  const words = query.value.toLowerCase().split(/\s+/).filter(Boolean);
  return pool.value.filter((e) => {
    if (trace.value && !e.traceTypes.includes(trace.value)) return false;
    if (tag.value && !e.tags.includes(tag.value)) return false;
    if (threeD.value && !e.threeD) return false;
    if (words.length === 0) return true;
    const haystack = `${e.title} ${e.id}`.toLowerCase();
    return words.every((w) => haystack.includes(w));
  });
});

const isFiltered = computed(
  () =>
    query.value !== '' ||
    category.value !== '' ||
    trace.value !== '' ||
    tag.value !== '' ||
    threeD.value,
);

function clearFilters(): void {
  query.value = '';
  category.value = '';
  trace.value = '';
  tag.value = '';
  threeD.value = false;
}

function toggleCategory(value: string): void {
  category.value = category.value === value ? '' : value;
}

function toggleTrace(value: string): void {
  trace.value = trace.value === value ? '' : value;
}

/** Query string for the current filters (the hash, the open example, is kept). */
function filtersToUrl(): void {
  const q = new URLSearchParams();
  if (query.value) q.set('q', query.value);
  if (category.value) q.set('category', category.value);
  if (trace.value) q.set('trace', trace.value);
  if (tag.value) q.set('tag', tag.value);
  if (threeD.value) q.set('3d', '1');
  if (internal.value) q.set('internal', '1');
  const search = q.toString();
  const url = `${location.pathname}${search ? `?${search}` : ''}${location.hash}`;
  history.replaceState(history.state, '', url);
}

function filtersFromUrl(): void {
  const q = new URLSearchParams(location.search);
  query.value = q.get('q') ?? '';
  const c = q.get('category') ?? '';
  category.value = categoryCounts.has(c) ? c : '';
  const t = q.get('trace') ?? '';
  trace.value = allTraceTypes.has(t) ? t : '';
  const g = q.get('tag') ?? '';
  tag.value = allTags.has(g) ? g : '';
  threeD.value = q.get('3d') === '1';
  internal.value = q.get('internal') === '1';
}

// ---- detail view ---------------------------------------------------------------------------

const byId = new Map(examples.map((e) => [e.id, e]));
const selected = ref<Entry | null>(null);
const dialog = ref<HTMLDialogElement | null>(null);

function idFromHash(): string {
  try {
    return decodeURIComponent(location.hash.slice(1));
  } catch {
    return '';
  }
}

async function show(entry: Entry | undefined): Promise<void> {
  selected.value = entry ?? null;
  await nextTick();
  const el = dialog.value;
  if (!el) return;
  if (entry && !el.open) {
    el.showModal();
    document.documentElement.classList.add('hc-gallery-locked');
  } else if (!entry && el.open) {
    el.close();
  }
}

function open(entry: Entry, event?: MouseEvent): void {
  // Let modified clicks (new tab / window) follow the link.
  if (event && (event.metaKey || event.ctrlKey || event.shiftKey || event.button !== 0)) return;
  event?.preventDefault();
  if (idFromHash() !== entry.id) history.pushState(history.state, '', `#${entry.id}`);
  void show(entry);
}

function close(): void {
  if (!selected.value) return;
  history.replaceState(history.state, '', `${location.pathname}${location.search}`);
  void show(undefined);
}

function onDialogClose(): void {
  document.documentElement.classList.remove('hc-gallery-locked');
  if (selected.value) close();
}

/** Clicks on the backdrop (outside the panel) close the dialog. */
function onDialogClick(event: MouseEvent): void {
  if (event.target === dialog.value) close();
}

function filterByTag(value: string): void {
  clearFilters();
  tag.value = value;
  close();
}

function filterByTrace(value: string): void {
  clearFilters();
  trace.value = value;
  close();
}

function syncFromHash(): void {
  void show(byId.get(idFromHash()));
}

let mounted = false;
watch([query, category, trace, tag, threeD, internal], () => {
  if (mounted) filtersToUrl();
});

onMounted(() => {
  filtersFromUrl();
  mounted = true;
  syncFromHash();
  window.addEventListener('popstate', syncFromHash);
});

onBeforeUnmount(() => {
  window.removeEventListener('popstate', syncFromHash);
  document.documentElement.classList.remove('hc-gallery-locked');
});
</script>

<template>
  <div class="hc-gallery">
    <header class="hc-gallery-header">
      <p class="hc-gallery-eyebrow">Gallery</p>
      <h1 class="hc-gallery-title">Every example, at a glance</h1>
      <p class="hc-gallery-lede">
        {{ examples.length }} examples, rendered by the same pipeline as the visual regression
        tests. Select one to run it live, read its source, and find the pages that explain it.
      </p>
    </header>

    <section class="hc-gallery-filters" aria-label="Filters">
      <div class="hc-gallery-search">
        <label class="hc-gallery-visually-hidden" for="hc-gallery-search">Search by title</label>
        <input
          id="hc-gallery-search"
          v-model="query"
          type="search"
          placeholder="Search by title"
          autocomplete="off"
          spellcheck="false"
        />
        <select v-model="tag" aria-label="Tag">
          <option value="">Any tag</option>
          <option v-for="t in tags" :key="t" :value="t">
            {{ t }} ({{ tagCounts.get(t) ?? 0 }})
          </option>
        </select>
      </div>

      <div class="hc-gallery-row" role="group" aria-label="Category">
        <span class="hc-gallery-row-label">Category</span>
        <button
          v-for="c in categories"
          :key="c"
          type="button"
          class="hc-gallery-chip"
          :aria-pressed="category === c"
          @click="toggleCategory(c)"
        >
          {{ categoryLabel(c) }} <span class="hc-gallery-count">{{ categoryCounts.get(c) }}</span>
        </button>
      </div>

      <div class="hc-gallery-row" role="group" aria-label="Trace type">
        <span class="hc-gallery-row-label">Trace type</span>
        <button
          v-for="t in traceTypes"
          :key="t"
          type="button"
          class="hc-gallery-chip hc-gallery-chip--mono"
          :aria-pressed="trace === t"
          @click="toggleTrace(t)"
        >
          {{ t }} <span class="hc-gallery-count">{{ traceCounts.get(t) ?? 0 }}</span>
        </button>
        <button
          type="button"
          class="hc-gallery-chip"
          :aria-pressed="threeD"
          :disabled="threeDCount === 0 && !threeD"
          :title="threeDCount === 0 ? 'No 3D-native examples yet' : undefined"
          @click="threeD = !threeD"
        >
          3D-native <span class="hc-gallery-count">{{ threeDCount }}</span>
        </button>
      </div>

      <div class="hc-gallery-status">
        <span aria-live="polite"> {{ filtered.length }} of {{ examples.length }} examples </span>
        <button v-if="isFiltered" type="button" class="hc-gallery-link" @click="clearFilters">
          Clear filters
        </button>
        <label v-if="internalCount > 0 && !category" class="hc-gallery-check">
          <input v-model="internal" type="checkbox" />
          Include {{ internalCount }} internal renderer tests
        </label>
      </div>
    </section>

    <ul v-if="filtered.length > 0" class="hc-gallery-grid">
      <li v-for="e in filtered" :key="e.id" class="hc-gallery-card">
        <a :href="`#${e.id}`" class="hc-gallery-card-link" @click="open(e, $event)">
          <span class="hc-gallery-thumb">
            <img
              :src="withBase(`/${e.thumbnail}`)"
              :width="e.thumbnailSize.width"
              :height="e.thumbnailSize.height"
              :alt="e.title"
              loading="lazy"
              decoding="async"
            />
          </span>
          <span class="hc-gallery-card-body">
            <span class="hc-gallery-card-eyebrow">
              {{ categoryLabel(e.category) }}
              <template v-if="cardTraces(e).length">· {{ cardTraces(e).join(', ') }}</template>
            </span>
            <span class="hc-gallery-card-title">{{ shortTitle(e.title) }}</span>
          </span>
        </a>
      </li>
    </ul>
    <div v-else class="hc-gallery-empty">
      <p v-if="examples.length === 0">
        No thumbnails yet. Run <code>pnpm gallery</code> to generate them.
      </p>
      <p v-else>
        No examples match these filters.
        <button type="button" class="hc-gallery-link" @click="clearFilters">Clear filters</button>
      </p>
    </div>

    <dialog
      ref="dialog"
      class="hc-gallery-dialog"
      :aria-labelledby="selected ? 'hc-gallery-dialog-title' : undefined"
      @close="onDialogClose"
      @click="onDialogClick"
    >
      <div v-if="selected" class="hc-gallery-panel">
        <header class="hc-gallery-panel-header">
          <div>
            <p class="hc-gallery-card-eyebrow">
              {{ categoryLabel(selected.category) }} · <code>{{ selected.id }}</code>
            </p>
            <h2 id="hc-gallery-dialog-title" class="hc-gallery-panel-title">
              {{ selected.title }}
            </h2>
          </div>
          <button type="button" class="hc-gallery-close" aria-label="Close" @click="close">
            <svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">
              <path d="M3 3l10 10M13 3L3 13" stroke="currentColor" stroke-width="1.5" />
            </svg>
          </button>
        </header>

        <!-- vp-doc: the source tab's code block takes the site's code styles. -->
        <div class="vp-doc hc-gallery-live">
          <Example :id="selected.id" :key="selected.id" />
        </div>

        <dl class="hc-gallery-facts">
          <template v-if="selected.pages.length">
            <dt>Documented in</dt>
            <dd>
              <ul class="hc-gallery-pages">
                <li v-for="p in selected.pages" :key="p.link">
                  <a :href="withBase(p.link)">{{ p.title }}</a>
                </li>
              </ul>
            </dd>
          </template>
          <template v-if="selected.traceTypes.length">
            <dt>Trace types</dt>
            <dd class="hc-gallery-tags">
              <button
                v-for="t in selected.traceTypes"
                :key="t"
                type="button"
                class="hc-gallery-chip hc-gallery-chip--mono"
                @click="filterByTrace(t)"
              >
                {{ t }}
              </button>
            </dd>
          </template>
          <dt>Tags</dt>
          <dd class="hc-gallery-tags">
            <button
              v-for="t in selected.tags"
              :key="t"
              type="button"
              class="hc-gallery-chip"
              @click="filterByTag(t)"
            >
              {{ t }}
            </button>
          </dd>
          <dt>Size</dt>
          <dd>{{ selected.size.width }} × {{ selected.size.height }} px</dd>
        </dl>
      </div>
    </dialog>
  </div>
</template>

<style>
.hc-gallery {
  max-width: 1376px;
  margin: 0 auto;
  padding: 40px 24px 96px;
}

.hc-gallery-header {
  max-width: 760px;
  margin-bottom: 28px;
}

.hc-gallery-eyebrow {
  margin: 0 0 8px;
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
  font-weight: 500;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--vp-c-brand-1);
}

.hc-gallery-title {
  margin: 0 0 12px;
  font-size: 32px;
  font-weight: 600;
  line-height: 1.2;
  letter-spacing: -0.01em;
  color: var(--hc-title);
}

.hc-gallery-lede {
  margin: 0;
  font-size: 15px;
  line-height: 1.6;
  color: var(--vp-c-text-2);
}

/* ---- filters ---- */

.hc-gallery-filters {
  display: flex;
  flex-direction: column;
  gap: 12px;
  margin-bottom: 24px;
  padding: 16px;
  border: 1px solid var(--hc-grid);
  border-radius: 4px;
  background: var(--hc-surface-1);
}

.hc-gallery-search {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.hc-gallery-search input,
.hc-gallery-search select {
  height: 34px;
  padding: 0 10px;
  border: 1px solid var(--hc-axis);
  border-radius: 3px;
  background: var(--hc-bg);
  font-size: 14px;
  color: var(--vp-c-text-1);
}

.hc-gallery-search input {
  flex: 1 1 240px;
  max-width: 440px;
}

.hc-gallery-search input::placeholder {
  color: var(--vp-c-text-3);
}

.hc-gallery-search select {
  flex: 0 1 220px;
  min-width: 0;
  cursor: pointer;
}

.hc-gallery-search input:focus,
.hc-gallery-search select:focus {
  border-color: var(--vp-c-brand-1);
  outline: none;
}

.hc-gallery-row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 6px;
}

.hc-gallery-row-label {
  flex: 0 0 88px;
  font-family: var(--vp-font-family-mono);
  font-size: 11px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--vp-c-text-3);
}

.hc-gallery-chip {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  height: 28px;
  padding: 0 10px;
  border: 1px solid var(--hc-axis);
  border-radius: 3px;
  font-size: 13px;
  color: var(--vp-c-text-2);
  transition:
    color 0.15s,
    border-color 0.15s,
    background-color 0.15s;
}

.hc-gallery-chip--mono {
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
}

.hc-gallery-chip:hover:not(:disabled) {
  border-color: var(--hc-zero);
  background: var(--hc-surface-3);
  color: var(--vp-c-text-1);
}

.hc-gallery-chip[aria-pressed='true'] {
  border-color: rgba(234, 42, 55, 0.6);
  background: var(--vp-c-brand-soft);
  color: var(--vp-c-brand-1);
}

.hc-gallery-chip:disabled {
  cursor: not-allowed;
  opacity: 0.45;
}

.hc-gallery-count {
  font-family: var(--vp-font-family-mono);
  font-size: 11px;
  color: var(--vp-c-text-3);
}

.hc-gallery-chip[aria-pressed='true'] .hc-gallery-count {
  color: inherit;
  opacity: 0.8;
}

.hc-gallery-status {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 8px 16px;
  padding-top: 4px;
  font-family: var(--vp-font-family-mono);
  font-size: 12px;
  color: var(--vp-c-text-3);
}

.hc-gallery-link {
  font-family: inherit;
  font-size: inherit;
  color: var(--vp-c-brand-1);
}

.hc-gallery-link:hover {
  color: var(--vp-c-brand-2);
  text-decoration: underline;
}

.hc-gallery-check {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  margin-left: auto;
  cursor: pointer;
}

.hc-gallery-check input {
  accent-color: var(--hc-red);
}

.hc-gallery-visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
}

/* ---- grid ---- */

.hc-gallery-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(256px, 1fr));
  gap: 16px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.hc-gallery-card-link {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow: hidden;
  border: 1px solid var(--hc-grid);
  border-radius: 4px;
  background: var(--hc-surface-1);
  color: inherit;
  text-decoration: none;
  transition:
    border-color 0.15s,
    transform 0.15s;
}

.hc-gallery-card-link:hover {
  border-color: var(--hc-zero);
  transform: translateY(-1px);
}

.hc-gallery-card-link:focus-visible {
  outline: 2px solid var(--vp-c-brand-1);
  outline-offset: 2px;
}

/* Every card's image area is 16:10; thumbnails of other shapes are letterboxed on the chart
   background (the default look's paper color), so they blend in. */
.hc-gallery-thumb {
  position: relative;
  display: block;
  aspect-ratio: 16 / 10;
  overflow: hidden;
  border-bottom: 1px solid var(--hc-grid);
  background: var(--hc-bg);
}

.hc-gallery-thumb img {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: contain;
  opacity: 0.92;
  transition: opacity 0.15s;
}

.hc-gallery-card-link:hover .hc-gallery-thumb img {
  opacity: 1;
}

.hc-gallery-card-body {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 10px 12px 12px;
}

.hc-gallery-card-eyebrow {
  margin: 0;
  font-family: var(--vp-font-family-mono);
  font-size: 11px;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  color: var(--vp-c-text-3);
}

.hc-gallery-card-eyebrow code {
  font-size: 11px;
  text-transform: none;
  color: var(--vp-c-text-2);
}

.hc-gallery-card-title {
  font-size: 14px;
  font-weight: 500;
  line-height: 1.4;
  color: var(--vp-c-text-1);
}

.hc-gallery-empty {
  padding: 48px 16px;
  border: 1px dashed var(--hc-axis);
  border-radius: 4px;
  text-align: center;
  color: var(--vp-c-text-2);
}

/* ---- detail dialog ---- */

html.hc-gallery-locked {
  overflow: hidden;
}

.hc-gallery-dialog {
  width: min(1080px, calc(100vw - 32px));
  max-width: none;
  max-height: calc(100dvh - 32px);
  margin: auto;
  padding: 0;
  border: 1px solid var(--hc-axis);
  border-radius: 6px;
  background: var(--hc-bg);
  color: var(--vp-c-text-1);
  box-shadow: var(--vp-shadow-5);
}

.hc-gallery-dialog::backdrop {
  background: rgba(0, 0, 0, 0.72);
  backdrop-filter: blur(2px);
}

.hc-gallery-panel {
  padding: 20px 24px 24px;
}

.hc-gallery-panel-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 16px;
}

.hc-gallery-panel-title {
  margin: 4px 0 0;
  font-size: 20px;
  font-weight: 600;
  line-height: 1.3;
  color: var(--hc-title);
}

.hc-gallery-close {
  display: grid;
  flex: 0 0 auto;
  place-items: center;
  width: 32px;
  height: 32px;
  border: 1px solid var(--hc-axis);
  border-radius: 3px;
  color: var(--vp-c-text-2);
}

.hc-gallery-close:hover {
  border-color: var(--hc-zero);
  color: var(--hc-title);
}

.hc-gallery-live .hc-example {
  margin: 16px 0;
}

.hc-gallery-facts {
  display: grid;
  grid-template-columns: 136px 1fr;
  gap: 10px 16px;
  margin: 0;
  font-size: 14px;
}

.hc-gallery-facts dt {
  padding-top: 5px;
  font-family: var(--vp-font-family-mono);
  font-size: 11px;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--vp-c-text-3);
}

.hc-gallery-facts dd {
  margin: 0;
  padding-top: 2px;
  color: var(--vp-c-text-2);
}

.hc-gallery-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.hc-gallery-pages {
  margin: 0;
  padding: 0;
  list-style: none;
}

.hc-gallery-pages a {
  color: var(--vp-c-brand-1);
  text-decoration: none;
}

.hc-gallery-pages a:hover {
  text-decoration: underline;
}

@media (max-width: 640px) {
  .hc-gallery {
    padding: 24px 16px 64px;
  }

  .hc-gallery-title {
    font-size: 26px;
  }

  .hc-gallery-row-label {
    flex-basis: 100%;
  }

  .hc-gallery-search input,
  .hc-gallery-search select {
    flex: 1 1 100%;
    max-width: none;
  }

  .hc-gallery-grid {
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 12px;
  }

  .hc-gallery-panel {
    padding: 16px;
  }

  .hc-gallery-facts {
    grid-template-columns: 1fr;
    gap: 4px;
  }

  .hc-gallery-facts dd {
    margin-bottom: 8px;
  }

  .hc-gallery-check {
    margin-left: 0;
  }
}
</style>
