/**
 * Generates the lazy font modules of Holochart's built-in default font (plan E2.18, E8.3): one
 * TypeScript module per face of TeX Gyre Heros, exporting the committed OTF file as a `data:` URL.
 *
 *   node scripts/fonts/generate-default-fonts.ts          # write the modules
 *   node scripts/fonts/generate-default-fonts.ts --check  # exit 1 when they are stale
 *
 * Why modules and not asset files: `@mk7s/holochart-render` imports each module with a dynamic
 * `import()`, which every bundler (Vite, webpack, esbuild, Rollup, rolldown) splits into its own
 * lazy chunk with no configuration, whereas `new URL('./font.otf', import.meta.url)` assets are
 * not handled the same way everywhere. The IIFE build does not use these modules: it loads the
 * OTF files shipped next to the script (see `packages/holochart/tsdown.config.ts`).
 *
 * `tests/build/default-fonts.test.ts` fails when a module is stale.
 */
import { readFileSync, readdirSync, rmSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/** Committed font sources (shipped as-is in the render package, with their license). */
export const FONT_SOURCE_DIR = 'packages/render/fonts';

/** Generated modules. */
export const FONT_MODULE_DIR = 'packages/render/src/fonts/generated';

/** The license file that must accompany the fonts wherever they ship. */
export const FONT_LICENSE_FILE = 'GUST-FONT-LICENSE.txt';

export const GEN_COMMAND = 'node scripts/fonts/generate-default-fonts.ts';

/** One face of the default family. */
export interface DefaultFontSource {
  /** OTF file in {@link FONT_SOURCE_DIR}; the module is `<basename>.ts`. */
  file: string;
  /** Human-readable face name for the module header. */
  name: string;
  weight: 400 | 700;
  style: 'normal' | 'italic';
}

/** TeX Gyre Heros 2.004 (GUST Font License), a free Helvetica-style family. */
export const DEFAULT_FONT_SOURCES: readonly DefaultFontSource[] = [
  {
    file: 'texgyreheros-regular.otf',
    name: 'TeX Gyre Heros Regular',
    weight: 400,
    style: 'normal',
  },
  { file: 'texgyreheros-bold.otf', name: 'TeX Gyre Heros Bold', weight: 700, style: 'normal' },
  { file: 'texgyreheros-italic.otf', name: 'TeX Gyre Heros Italic', weight: 400, style: 'italic' },
  {
    file: 'texgyreheros-bolditalic.otf',
    name: 'TeX Gyre Heros Bold Italic',
    weight: 700,
    style: 'italic',
  },
];

/** Repo-relative path of the generated module for a face. */
export function fontModulePath(source: DefaultFontSource): string {
  return `${FONT_MODULE_DIR}/${source.file.replace(/\.otf$/, '')}.ts`;
}

function moduleSource(source: DefaultFontSource, bytes: Buffer): string {
  const url = `data:font/otf;base64,${bytes.toString('base64')}`;
  // The `/*!` notice is a legal comment: bundlers and minifiers keep it in the emitted chunk.
  return [
    `// Generated by \`${GEN_COMMAND}\` from ${FONT_SOURCE_DIR}/${source.file}. Do not edit.`,
    '',
    '/*!',
    ` * ${source.name} 2.004. Copyright 2006, 2009 for TeX Gyre extensions by B. Jackowski and`,
    ' * J.M. Nowacki (on behalf of TeX users groups). Released under the GUST Font License',
    ` * (LPPL 1.3c): see ${FONT_LICENSE_FILE} in the fonts/ folder of @mk7s/holochart-render.`,
    ' */',
    '',
    `/** ${source.name} (OpenType CFF, ${bytes.length} bytes) as a \`data:\` URL. */`,
    `export default '${url}';`,
    '',
  ].join('\n');
}

/** Every generated module, keyed by repo-relative path. */
export function generateFontModules(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const source of DEFAULT_FONT_SOURCES) {
    const bytes = readFileSync(path.join(REPO_ROOT, FONT_SOURCE_DIR, source.file));
    out[fontModulePath(source)] = moduleSource(source, bytes);
  }
  return out;
}

function main(): void {
  const check = process.argv.includes('--check');
  const files = generateFontModules();
  const dir = path.join(REPO_ROOT, FONT_MODULE_DIR);
  let stale = 0;
  if (!check) mkdirSync(dir, { recursive: true });
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(REPO_ROOT, rel);
    let current = '';
    try {
      current = readFileSync(abs, 'utf8');
    } catch {
      // missing: stale
    }
    if (current === content) continue;
    stale++;
    if (check) console.error(`${rel} is stale`);
    else writeFileSync(abs, content);
  }
  // Modules of faces that no longer exist.
  const wanted = new Set(Object.keys(files).map((rel) => path.basename(rel)));
  let names: string[];
  try {
    names = readdirSync(dir);
  } catch {
    names = [];
  }
  for (const name of names) {
    if (wanted.has(name)) continue;
    stale++;
    if (check) console.error(`${FONT_MODULE_DIR}/${name} is not generated from any font`);
    else rmSync(path.join(dir, name));
  }
  if (check && stale > 0) {
    console.error(`Run \`${GEN_COMMAND}\`.`);
    process.exit(1);
  }
  console.log(check ? 'Font modules are up to date.' : `Wrote ${stale} font module(s).`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
