/**
 * Generates the JavaScript API reference (plan E19.7): TypeDoc + typedoc-plugin-markdown over the
 * public packages, written to `reference/api/` as VitePress pages. Runs before `dev` and `build`;
 * the output is gitignored.
 *
 * - Packages are documented from their TypeScript sources (`src/index.ts`), so no build is needed.
 * - Thin packages are tolerated: a package without exports gets a placeholder page, a package that
 *   only re-exports others (the `@mk7s/holochart` bundle today) gets a page linking to them instead
 *   of a duplicate copy, and TypeScript errors in work-in-progress packages don't fail the docs
 *   build (`skipErrorChecking`).
 * - Pages are wrapped in `<div v-pre>` (TSDoc comments may contain `{{`), get frontmatter, and are
 *   formatted with the repo's Prettier config so `prettier --check .` stays clean.
 * - `reference/api/sidebar.json` is written for `.vitepress/config.ts`.
 *
 * Usage: `node --conditions=source scripts/gen-api.ts [--strict]`. Without `--strict`, a TypeDoc
 * failure writes placeholder pages and a warning instead of failing the docs build.
 */
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { Application, LogLevel, type TypeDocOptions } from 'typedoc';
import type { PluginOptions } from 'typedoc-plugin-markdown';

const DOCS_ROOT = fileURLToPath(new URL('..', import.meta.url));
const REPO_ROOT = path.resolve(DOCS_ROOT, '../..');
const OUT_DIR = path.join(DOCS_ROOT, 'reference/api');
const LINK_ROOT = '/reference/api/';
const STRICT = process.argv.includes('--strict');

/** Public packages in the API reference, in sidebar order. */
const PACKAGES = ['packages/holochart', 'packages/runtime', 'packages/core', 'packages/render'];

interface SidebarItem {
  text: string;
  link: string;
}

interface Pkg {
  name: string;
  dir: string;
  source: string;
}

/** `export * from 'x'` / `export * as ns from 'x'` statements of a module. */
function reexports(source: string): { from: string; as?: string }[] {
  const out: { from: string; as?: string }[] = [];
  for (const m of source.matchAll(
    /^\s*export\s+\*\s+(?:as\s+(\w+)\s+)?from\s+['"]([^'"]+)['"]/gm,
  )) {
    out.push({ from: m[2] as string, ...(m[1] ? { as: m[1] } : {}) });
  }
  return out;
}

/** Export statements that are neither `export {}` nor `export * …` re-exports. */
function ownExports(source: string): boolean {
  const code = source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/^\s*\/\/.*$/gm, '');
  return /^\s*export\s+(?!\*|\{\s*\}\s*;?\s*$)/m.test(code);
}

/** Directory name for a package page, e.g. `@mk7s/holochart-core` → `holochart-core`. */
function slug(packageName: string): string {
  return packageName.replace(/^@[^/]+\//, '');
}

async function listMarkdown(dir: string, rel = ''): Promise<string[]> {
  const out: string[] = [];
  for (const e of await readdir(path.join(dir, rel), { withFileTypes: true })) {
    const child = rel ? `${rel}/${e.name}` : e.name;
    if (e.isDirectory()) out.push(...(await listMarkdown(dir, child)));
    else if (e.name.endsWith('.md')) out.push(child);
  }
  return out.sort();
}

function firstHeading(markdown: string): string | undefined {
  return /^#\s+(.+)$/m
    .exec(markdown)?.[1]
    ?.replace(/\\([<>])/g, '$1')
    .trim();
}

async function writeFormatted(file: string, source: string): Promise<void> {
  await mkdir(path.dirname(file), { recursive: true });
  const config = await prettier.resolveConfig(file);
  await writeFile(file, await prettier.format(source, { ...config, filepath: file }));
}

/** Add frontmatter and a v-pre wrapper to a page body. */
function wrapPage(markdown: string, title: string): string {
  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    'editLink: false',
    'outline: [2, 3]',
    '---',
    '',
    '<!-- Generated by apps/docs/scripts/gen-api.ts (TypeDoc). Do not edit. -->',
    '',
    '<div v-pre>',
    '',
    markdown.trim(),
    '',
    '</div>',
    '',
  ].join('\n');
}

async function runTypeDoc(packages: readonly Pkg[]): Promise<boolean> {
  // With a single package TypeDoc writes it at the output root; keep the per-package layout.
  const only = packages.length === 1 ? packages[0] : undefined;
  const options: TypeDocOptions & PluginOptions = {
    entryPointStrategy: 'packages',
    entryPoints: packages.map((p) => p.dir),
    packageOptions: {
      entryPoints: ['src/index.ts'],
      excludeInternal: true,
      excludePrivate: true,
      readme: 'none',
      // Work-in-progress packages may not type-check; document them anyway.
      skipErrorChecking: true,
    },
    plugin: ['typedoc-plugin-markdown'],
    out: only ? path.join(OUT_DIR, slug(only.name)) : OUT_DIR,
    readme: 'none',
    name: 'Holochart API',
    skipErrorChecking: true,
    excludeInternal: true,
    excludePrivate: true,
    excludeExternals: true,
    disableSources: true,
    logLevel: LogLevel.Warn,
    // Internal helper types referenced from public signatures are expected for now.
    validation: { notExported: false, invalidLink: true, rewrittenLink: true },
    // Markdown output tuned for VitePress.
    entryFileName: 'index',
    excludeScopesInPaths: true,
    hidePageHeader: true,
    hideBreadcrumbs: true,
    useCodeBlocks: true,
    sanitizeComments: true,
    parametersFormat: 'table',
    interfacePropertiesFormat: 'table',
    classPropertiesFormat: 'table',
    typeDeclarationFormat: 'table',
    indexFormat: 'table',
  };
  const app = await Application.bootstrapWithPlugins(options);
  const project = await app.convert();
  if (!project) return false;
  await app.generateOutputs(project);
  return true;
}

async function main(): Promise<void> {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const packages: Pkg[] = [];
  for (const rel of PACKAGES) {
    const dir = path.join(REPO_ROOT, rel);
    const entry = path.join(dir, 'src/index.ts');
    if (!existsSync(entry)) continue;
    const { name } = JSON.parse(await readFile(path.join(dir, 'package.json'), 'utf8')) as {
      name: string;
    };
    packages.push({ name, dir, source: await readFile(entry, 'utf8') });
  }
  const names = new Set(packages.map((p) => p.name));
  const documented = packages.filter((p) => ownExports(p.source));
  // A package that only re-exports documented packages gets a map page, not a second copy.
  const aggregates = packages.filter((p) => {
    const re = reexports(p.source);
    return !ownExports(p.source) && re.length > 0 && re.every((r) => names.has(r.from));
  });
  // Everything else with exports (including internal `export * from './x.ts'`) goes to TypeDoc.
  documented.push(
    ...packages.filter(
      (p) => !documented.includes(p) && !aggregates.includes(p) && reexports(p.source).length > 0,
    ),
  );
  documented.sort((a, b) => packages.indexOf(a) - packages.indexOf(b));
  const empty = packages.filter((p) => !documented.includes(p) && !aggregates.includes(p));
  const notes = new Map<string, string>();
  for (const p of empty) {
    notes.set(
      p.name,
      'This package does not export a public API yet. Its reference appears here once it does.',
    );
  }

  if (documented.length > 0 && !(await runTypeDoc(documented))) {
    // Don't take the whole docs site down with the API pages; `--strict` (CI) fails instead.
    const message = 'TypeDoc failed to convert the API packages; writing placeholder pages.';
    if (STRICT) throw new Error(message);
    console.warn(`warning: ${message}`);
    for (const p of documented.splice(0)) {
      notes.set(p.name, 'The API reference for this package could not be generated in this build.');
    }
  }

  // Post-process TypeDoc's pages. TypeDoc's own multi-package index is replaced below.
  const pages = (await listMarkdown(OUT_DIR)).filter((p) => p !== 'index.md');
  for (const rel of pages) {
    const abs = path.join(OUT_DIR, rel);
    const raw = await readFile(abs, 'utf8');
    await writeFormatted(abs, wrapPage(raw, firstHeading(raw) ?? rel.replace(/\.md$/, '')));
  }

  for (const p of aggregates) {
    const lines = reexports(p.source).map(({ from, as }) => {
      const target = names.has(from) ? `[${from}](${LINK_ROOT}${slug(from)}/)` : `\`${from}\``;
      return as
        ? `- \`${as}\`: the ${target} namespace (\`import { ${as} } from '${p.name}'\`)`
        : `- everything exported by ${target}`;
    });
    const body = [
      `# ${p.name}`,
      '',
      'The full bundle. It re-exports the packages below, so every symbol is documented on the page of the package that defines it:',
      '',
      ...lines,
      '',
    ].join('\n');
    await writeFormatted(path.join(OUT_DIR, slug(p.name), 'index.md'), wrapPage(body, p.name));
  }
  for (const [name, note] of notes) {
    await writeFormatted(
      path.join(OUT_DIR, slug(name), 'index.md'),
      wrapPage(`# ${name}\n\n${note}\n`, name),
    );
  }

  const status = (p: Pkg): string =>
    documented.includes(p)
      ? 'documented'
      : aggregates.includes(p)
        ? 're-exports other packages'
        : notes.has(p.name) && empty.includes(p)
          ? 'no public exports yet'
          : 'generation failed';
  const overview = [
    '# JavaScript API reference',
    '',
    'Generated with TypeDoc from the TypeScript sources of the public packages. Figure attributes (traces, layout, config) are documented in the [attribute reference](/reference/), which is generated from the schema.',
    '',
    '| Package | Status |',
    '| --- | --- |',
    ...packages.map((p) => `| [${p.name}](${LINK_ROOT}${slug(p.name)}/) | ${status(p)} |`),
    '',
  ].join('\n');
  await writeFormatted(
    path.join(OUT_DIR, 'index.md'),
    wrapPage(overview, 'JavaScript API reference'),
  );

  // Packages only: each package's index page lists its symbols. Listing every symbol here would
  // be server-rendered into every API page (hundreds of KB each).
  const sidebar: SidebarItem[] = [
    { text: 'Overview', link: LINK_ROOT },
    ...packages.map((p) => ({ text: p.name, link: `${LINK_ROOT}${slug(p.name)}/` })),
  ];
  await writeFormatted(path.join(OUT_DIR, 'sidebar.json'), JSON.stringify(sidebar));

  console.log(
    `API reference → ${path.relative(REPO_ROOT, OUT_DIR)}: ` +
      packages.map((p) => `${p.name} (${status(p)})`).join(', '),
  );
}

await main();
