/**
 * TypeScript type generation from the attribute schema (plan E1.2).
 *
 * Turns a schema tree into named, documented input interfaces (`Layout`, `LayoutMargin`,
 * `TraceScatterMarker`, …). The inferred types from `InferInput` are exact but anonymous, so
 * editor hovers show a wall of structure; named interfaces with JSDoc read much better in
 * autocompletion and API docs, which is why generated types are checked in alongside the schema.
 *
 * Pure string building: no Node APIs, so it can run anywhere (CLI, tests, the playground).
 */
import type { AttrSpec, ItemsNode, ObjectNode, Primitive, SchemaNode } from '../schema/types.ts';

/** Options for {@link generateTypes} and {@link generateTraceTypes}. */
export interface GenerateTypesOptions {
  /**
   * Module specifier the helper types (`TypedArray`, `DataArray`, `ColorScale`, `AnyFunction`)
   * are imported from. Defaults to `'../schema/types.ts'`, the right path for files written to
   * `packages/core/src/generated/`.
   */
  readonly importFrom?: string;
  /** Header comment text (one `//` line per line). Defaults to a "generated, do not edit" note. */
  readonly header?: string;
}

/** A trace type and its full (registry-merged) schema, as passed to {@link generateTraceTypes}. */
export interface TraceTypeSource {
  /** Trace type, e.g. `'scatter'`. */
  readonly type: string;
  /** Full trace schema, e.g. from `registry.getTraceSchema(type)`. */
  readonly schema: ObjectNode;
}

/** The default header written at the top of every generated file. */
export const DEFAULT_GENERATED_HEADER =
  'Generated by tools/schema-gen from the attribute schema (plan E1.2). Do not edit by hand.\n' +
  'Regenerate with `pnpm --filter @mk7s/holochart-schema-gen gen`.';

const DEFAULT_IMPORT_FROM = '../schema/types.ts';

/** Helper types from `schema/types.ts` that generated code may reference. */
type HelperType = 'AnyFunction' | 'ColorScale' | 'DataArray' | 'TypedArray';

/** The trace type used when `type` is omitted; its `type` discriminant is optional. */
const DEFAULT_TRACE_TYPE = 'scatter';

interface Context {
  readonly helpers: Set<HelperType>;
  /** Declarations in emission order (parents before children). */
  readonly decls: string[];
  readonly names: Set<string>;
}

/** Replaces a property's generated type (used for the trace `type` discriminant). */
interface PropOverride {
  readonly type: string;
  readonly optional: boolean;
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function pascal(key: string): string {
  return key
    .split(/[^A-Za-z0-9]+/)
    .filter((s) => s !== '')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

/** Escapes text for use inside a template literal type. */
function templateText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function propName(key: string): string {
  return IDENTIFIER.test(key) ? key : quote(key);
}

function literal(v: Primitive): string {
  if (typeof v === 'string') return quote(v);
  // `Infinity`/`NaN` have no literal type; `number` is the closest sound widening.
  if (typeof v === 'number' && !Number.isFinite(v)) return 'number';
  return String(v);
}

function union(members: readonly string[]): string {
  return [...new Set(members)].join(' | ');
}

/** `readonly T[]`, parenthesizing `T` when it is not a single simple member. */
function readonlyArray(members: readonly string[]): string {
  const unique = [...new Set(members)];
  const only = unique.length === 1 ? unique[0] : undefined;
  const simple = only !== undefined && !only.startsWith('readonly ') && !only.includes('=>');
  return simple ? `readonly ${only}[]` : `readonly (${unique.join(' | ')})[]`;
}

/** Union members for a leaf attribute's input type. */
function leafMembers(spec: AttrSpec, ctx: Context): string[] {
  const extras = (spec.extras ?? []).map(literal);
  switch (spec.valType) {
    case 'number':
    case 'integer':
    case 'angle': {
      if (spec.arrayOk === true) {
        ctx.helpers.add('TypedArray');
        return ['number', 'readonly number[]', 'TypedArray', ...extras];
      }
      return ['number', ...extras];
    }
    case 'string':
    case 'color':
      return spec.arrayOk === true ? ['string', 'readonly string[]'] : ['string'];
    case 'boolean':
      return spec.arrayOk === true ? ['boolean', 'readonly boolean[]'] : ['boolean'];
    case 'enumerated': {
      const values = (spec.values ?? []).map(literal);
      if (values.length === 0) return ['never'];
      return spec.arrayOk === true ? [...values, readonlyArray(values)] : values;
    }
    case 'flaglist': {
      const flags = (spec.flags ?? []).map(quote);
      const combos = flags.length > 0 ? [...flags, `\`\${${union(flags)}}+\${string}\``] : [];
      const members = [...combos, ...extras];
      if (members.length === 0) return ['string'];
      return spec.arrayOk === true ? [...members, readonlyArray(members)] : members;
    }
    case 'colorlist':
      return ['readonly string[]'];
    case 'colorscale':
      ctx.helpers.add('ColorScale');
      return ['ColorScale'];
    case 'subplotid': {
      if (typeof spec.dflt !== 'string') return ['string', ...extras];
      return [quote(spec.dflt), `\`${templateText(spec.dflt)}\${number}\``, ...extras];
    }
    case 'data_array':
      ctx.helpers.add('DataArray');
      return ['DataArray'];
    case 'info_array': {
      const items = spec.items;
      if (items === undefined) return ['readonly unknown[]'];
      if (!isSpecList(items)) return [readonlyArray(leafMembers(items, ctx))];
      const types = items.map((item) => union(leafMembers(item, ctx)));
      // A free-length array with per-position specs can be shorter or longer than the tuple, so
      // only the element union is sound.
      if (spec.freeLength === true) return [readonlyArray(types.length ? types : ['unknown'])];
      return [`readonly [${types.join(', ')}]`];
    }
    case 'any':
      return ['unknown'];
    case 'function':
      ctx.helpers.add('AnyFunction');
      return ['AnyFunction'];
  }
}

function isSpecList(items: AttrSpec | readonly AttrSpec[]): items is readonly AttrSpec[] {
  return Array.isArray(items);
}

function escapeComment(s: string): string {
  return s.replace(/\*\//g, '*\\/');
}

function jsonText(v: unknown): string | undefined {
  try {
    return JSON.stringify(v);
  } catch {
    // Cyclic or otherwise unserializable defaults are simply left out of the docs.
    return undefined;
  }
}

/** JSDoc body lines for a node: description, range, default, deprecation, since. */
function docLines(node: SchemaNode): string[] {
  const paragraphs: string[][] = [];
  if (node.description !== undefined && node.description.trim() !== '') {
    paragraphs.push(
      node.description
        .trim()
        .split('\n')
        .map((l) => l.trimEnd()),
    );
  }
  if (node.kind === 'attr') {
    const { min, max } = node;
    if (min !== undefined && max !== undefined) paragraphs.push([`Range: ${min} – ${max}`]);
    else if (min !== undefined) paragraphs.push([`Minimum: ${min}`]);
    else if (max !== undefined) paragraphs.push([`Maximum: ${max}`]);
    if (node.dflt !== undefined) {
      const json = jsonText(node.dflt);
      if (json !== undefined) paragraphs.push([`@defaultValue \`${json}\``]);
    }
  }
  if (node.deprecated !== undefined) paragraphs.push([`@deprecated ${node.deprecated}`]);
  if (node.since !== undefined) paragraphs.push([`@since ${node.since}`]);
  return paragraphs.flatMap((p, i) => (i === 0 ? p : ['', ...p]));
}

function docComment(lines: readonly string[], indent: string): string {
  if (lines.length === 0) return '';
  const body = lines.map((l) => (l === '' ? `${indent} *` : `${indent} * ${escapeComment(l)}`));
  return `${indent}/**\n${body.join('\n')}\n${indent} */\n`;
}

function reserveName(ctx: Context, name: string): void {
  // Two paths mapping to one name (e.g. `x_axis` and `xAxis` under one parent) would silently
  // merge interfaces; failing loudly lets the schema author rename one of them.
  if (ctx.names.has(name)) throw new Error(`generateTypes: duplicate interface name '${name}'`);
  ctx.names.add(name);
}

function emitObject(
  node: ObjectNode,
  name: string,
  ctx: Context,
  doc: readonly string[],
  overrides: Readonly<Record<string, PropOverride>> = {},
): void {
  reserveName(ctx, name);
  // Reserve the slot first so parents precede their nested interfaces in the output.
  const slot = ctx.decls.push('') - 1;
  const props: string[] = [];
  const children: [string, SchemaNode | undefined][] = Object.entries(node.children);
  for (const key of Object.keys(overrides)) {
    if (!Object.hasOwn(node.children, key)) children.unshift([key, undefined]);
  }
  for (const [key, child] of children) {
    const override = Object.hasOwn(overrides, key) ? overrides[key] : undefined;
    const prop = propName(key);
    const jsdoc = docComment(child ? docLines(child) : [], '  ');
    if (override !== undefined) {
      props.push(`${jsdoc}  ${prop}${override.optional ? '?' : ''}: ${override.type};`);
    } else if (child === undefined) {
      continue;
    } else if (child.kind === 'attr') {
      props.push(`${jsdoc}  ${prop}?: ${union(leafMembers(child, ctx))};`);
    } else if (child.kind === 'object') {
      const childName = name + pascal(key);
      emitObject(child, childName, ctx, docLines(child));
      props.push(`${jsdoc}  ${prop}?: ${childName};`);
      if (child.subplot !== undefined) props.push(subplotIndex(key, childName));
    } else {
      const itemName = name + pascal(child.itemName);
      emitObject(child.item, itemName, ctx, itemDoc(key, child));
      props.push(`${jsdoc}  ${prop}?: Array<${itemName}>;`);
    }
  }
  const head = docComment(doc, '');
  ctx.decls[slot] =
    props.length === 0
      ? // An empty interface is flagged by lint as `{}` (anything); an empty object type is exact.
        `${head}export type ${name} = Record<string, never>;`
      : `${head}export interface ${name} {\n${props.join('\n')}\n}`;
}

function subplotIndex(key: string, typeName: string): string {
  const doc = docComment(
    [`Further \`${key}\` containers (\`${key}2\`, \`${key}3\`, …), with the same attributes.`],
    '  ',
  );
  return `${doc}  [key: \`${templateText(key)}\${number}\`]: ${typeName} | undefined;`;
}

function itemDoc(key: string, node: ItemsNode): string[] {
  const lines = [`One item of \`${key}\`.`];
  const templated = `Template defaults for every item go in \`${node.itemName}defaults\`.`;
  return [...lines, '', templated];
}

function newContext(): Context {
  return { helpers: new Set(), decls: [], names: new Set() };
}

function render(ctx: Context, options: GenerateTypesOptions | undefined, extra: string[]): string {
  const header = (options?.header ?? DEFAULT_GENERATED_HEADER)
    .split('\n')
    .map((l) => (l === '' ? '//' : `// ${l}`))
    .join('\n');
  const parts = [header];
  if (ctx.helpers.size > 0) {
    const names = [...ctx.helpers].sort().join(', ');
    parts.push(
      `import type { ${names} } from ${quote(options?.importFrom ?? DEFAULT_IMPORT_FROM)};`,
    );
  }
  parts.push(...ctx.decls, ...extra);
  return `${parts.join('\n\n')}\n`;
}

/**
 * Generate TypeScript input interfaces for a schema.
 *
 * Emits `export interface <name>` and one interface per nested container, named
 * `<Parent><PascalKey>` (`Layout` → `LayoutMargin` → …). Item arrays become `Array<<Parent><Item>>`
 * and subplot families (`xaxis`) also accept numbered keys (`xaxis2`) via a template-literal index
 * signature. Every property is optional (these describe user input), and carries JSDoc built from
 * the schema's description, range, default, deprecation and `since` metadata.
 *
 * @param root - The schema to describe, e.g. `layoutSchema`.
 * @param name - Name of the root interface, e.g. `'Layout'`.
 * @returns Deterministic TypeScript source (not Prettier-formatted).
 * @throws If two containers map to the same interface name.
 *
 * @example
 * ```ts
 * const src = generateTypes(layoutSchema, 'Layout');
 * // export interface Layout { width?: number; margin?: LayoutMargin; ... }
 * ```
 */
export function generateTypes(
  root: ObjectNode,
  name: string,
  options?: GenerateTypesOptions,
): string {
  const ctx = newContext();
  emitObject(root, name, ctx, docLines(root));
  return render(ctx, options, []);
}

/**
 * Generate one `Trace<PascalType>` interface per trace type plus the discriminated union
 * `export type Data = TraceScatter | TraceBar | …` (in the order given).
 *
 * The schema's `type` string attribute is replaced by a literal discriminant: required for every
 * type except `'scatter'`, which is optional because a trace without `type` is a scatter trace.
 * With no traces, `Data` is `never`: no trace object is valid when no trace types are registered.
 *
 * @param traces - Trace types with their full schemas, e.g. from `registry.getTraceSchema(type)`.
 * @returns Deterministic TypeScript source (not Prettier-formatted).
 * @throws If two containers map to the same interface name.
 */
export function generateTraceTypes(
  traces: ReadonlyArray<TraceTypeSource>,
  options?: GenerateTypesOptions,
): string {
  const ctx = newContext();
  const names: string[] = [];
  for (const { type, schema } of traces) {
    const name = `Trace${pascal(type)}`;
    names.push(name);
    const discriminant: PropOverride = {
      type: quote(type),
      optional: type === DEFAULT_TRACE_TYPE,
    };
    emitObject(schema, name, ctx, docLines(schema), { type: discriminant });
  }
  const dataDoc = docComment(
    ['Any trace, discriminated on `type` (a trace without `type` is a scatter trace).'],
    '',
  );
  const data = `${dataDoc}export type Data = ${names.length > 0 ? names.join(' | ') : 'never'};`;
  return render(ctx, options, [data]);
}
