/**
 * The data modules of `packages/traces-geo/src/basemap/generated/`: each is a TopoJSON topology
 * as a JSON string, which `JSON.parse` reads about twice as fast as the engine parses the same
 * data as an object literal (docs/release/bundle-size.md, "Geo candidates").
 */
import { gzipSync } from 'node:zlib';
import type { Topology } from 'topojson-specification';
import type { Resolution } from './config.ts';
import { NATURAL_EARTH_TAG, NATURAL_EARTH_VERSION } from './sources.ts';

/** The two chunks of a resolution. */
export type Part = 'base' | 'extras';

const CONTENTS: Readonly<Record<Part, string>> = {
  base: 'countries and land',
  extras: 'lakes, rivers and subunits',
};

/** The file name of a data module, e.g. `base-110m.ts`. */
export function moduleName(part: Part, resolution: Resolution): string {
  return `${part}-${resolution}m.ts`;
}

/** `text` as a single-quoted JavaScript string literal. */
function literal(text: string): string {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** The statement a minifier leaves of a data module: what a bundle's chunk holds. */
function body(topology: Topology): string {
  return `export default ${literal(JSON.stringify(topology))};\n`;
}

/** The source text of a data module. */
export function moduleText(topology: Topology, part: Part, resolution: Resolution): string {
  return (
    '// Generated by tools/geo-data (`pnpm --filter @mk7s/holochart-geo-data build`). Do not edit.\n' +
    `// Natural Earth ${NATURAL_EARTH_VERSION} (public domain) at 1:${resolution}m: ${CONTENTS[part]},\n` +
    `// from github.com/nvkelso/natural-earth-vector at ${NATURAL_EARTH_TAG}. TopoJSON, as a JSON string.\n` +
    body(topology)
  );
}

/** Sizes of a data module in bytes: minified, and gzipped at level 9 as size-limit does. */
export function moduleSize(topology: Topology): { min: number; gzip: number } {
  const bytes = Buffer.from(body(topology), 'utf8');
  return { min: bytes.length, gzip: gzipSync(bytes, { level: 9 }).length };
}
