/**
 * The checked-in data modules of `packages/traces-geo/src/basemap/generated/`: that they are
 * what the build writes, and what they weigh.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { gzipSync } from 'node:zlib';
import type { Topology } from 'topojson-specification';
import { describe, expect, it } from 'vitest';
import { buildBasemap } from './build.ts';
import { GRID, RESOLUTIONS, type Resolution } from './config.ts';
import { moduleName, moduleSize, moduleText, type Part } from './emit.ts';
import { cacheIsFilled, NATURAL_EARTH_TAG, NATURAL_EARTH_VERSION, readSource } from './sources.ts';

const OUT_DIR = path.resolve(
  import.meta.dirname,
  '../../../packages/traces-geo/src/basemap/generated',
);
const PARTS: Part[] = ['base', 'extras'];

/**
 * Ceilings on each chunk, min + gzip in kB (1 kB = 1000 bytes), a few percent above what the
 * build gives today: 31.3, 8.7, 178.3 and 104.9. ADR-024's targets are about 40 kB for 1:110m
 * and 235 kB for 1:50m with all layers. Raise a ceiling only with a reason in the README.
 */
const CEILINGS_KB: Record<Resolution, Record<Part, number>> = {
  110: { base: 32, extras: 9 },
  50: { base: 181, extras: 107 },
};

function read(part: Part, resolution: Resolution): string {
  return readFileSync(path.join(OUT_DIR, moduleName(part, resolution)), 'utf8');
}

/** The module without its header comment: what a bundler's chunk holds. */
function body(text: string): string {
  return text.replace(/^\/\/.*\n/gm, '');
}

/** The topology a module exports, read back from its source text. */
function topologyOf(text: string): Topology {
  const literal = /^export default '(.*)';$/m.exec(text)?.[1];
  if (literal === undefined) throw new Error('not a data module');
  return JSON.parse(literal.replace(/\\(['\\])/g, '$1')) as Topology;
}

describe.each(RESOLUTIONS)('data modules at 1:%im', (resolution) => {
  it.each(PARTS)('%s: says where it comes from and uses the configured grid', (part) => {
    const text = read(part, resolution);
    expect(text).toMatch(/^\/\/ Generated by tools\/geo-data/);
    expect(text).toContain(`Natural Earth ${NATURAL_EARTH_VERSION}`);
    expect(text).toContain(`natural-earth-vector at ${NATURAL_EARTH_TAG}`);
    const grid = GRID[resolution];
    expect(topologyOf(text).transform).toEqual({
      scale: [360 / grid, 180 / grid],
      translate: [-180, -90],
    });
  });

  it.each(PARTS)('%s: stays under its size ceiling', (part) => {
    const text = read(part, resolution);
    const gzip = gzipSync(Buffer.from(body(text), 'utf8'), { level: 9 }).length;
    expect(moduleSize(topologyOf(text)).gzip).toBe(gzip);
    expect(gzip / 1000).toBeLessThan(CEILINGS_KB[resolution][part]);
  });

  it('has the objects of its part', () => {
    expect(Object.keys(topologyOf(read('base', resolution)).objects).sort()).toEqual([
      'countries',
      'land',
    ]);
    expect(Object.keys(topologyOf(read('extras', resolution)).objects).sort()).toEqual([
      'lakes',
      'rivers',
      'subunits',
    ]);
  });

  // Needs the Natural Earth files in `.cache/`, which only a machine that ran the build has.
  it.skipIf(!cacheIsFilled([resolution]))(
    'is what the build writes from the pinned sources',
    async () => {
      const built = buildBasemap(
        {
          countries: await readSource(resolution, 'countries', { offline: true }),
          lakes: await readSource(resolution, 'lakes', { offline: true }),
          rivers: await readSource(resolution, 'rivers', { offline: true }),
          subunits: await readSource(resolution, 'subunits', { offline: true }),
        },
        { grid: GRID[resolution] },
      );
      for (const part of PARTS) {
        expect(moduleText(built[part], part, resolution) === read(part, resolution), part).toBe(
          true,
        );
      }
    },
  );
});

describe('all layers together', () => {
  it.each([
    [110, 41],
    [50, 286],
  ] as [Resolution, number][])('1:%im stays under %i kB gzip', (resolution, ceiling) => {
    const total = PARTS.reduce(
      (sum, part) =>
        sum + gzipSync(Buffer.from(body(read(part, resolution)), 'utf8'), { level: 9 }).length,
      0,
    );
    expect(total / 1000).toBeLessThan(ceiling);
  });
});
